// Editorial promises describe the next screen, not a guaranteed business outcome.
// The same copy is used at article entry, beside the example, and in the reading bar.
const C = (ko, en, previewKo, previewEn, noteKo = "", noteEn = "") => ({ ko: { action: ko, preview: previewKo, note: noteKo }, en: { action: en, preview: previewEn, note: noteEn } });
export const BLOG_CONVERSION = {
  "simpson-paradox-conversion-rate": C("구성 이동과 내부 변화 나눠보기", "Split composition shift from within-group change", "전체 전환율이 변했을 때 구성 비중과 집단 안의 변화를 구분하는 예시입니다.", "Explore how composition and within-group changes affect an overall rate.", "예시는 가입자 구성 비중을 나눕니다. 내 파일로는 묶음별 합계의 비율을 먼저 확인합니다.", "The example splits a signup share. With your file, the inline check compares ratios of group totals first."),
  "user-churn-survival-analysis": C("이탈 시점 생존곡선 보기", "See a churn-timing survival curve", "아직 이탈하지 않은 사용자도 포함해 이탈 시점과 관측 기간을 함께 읽는 예시입니다.", "Read churn timing and observation windows while retaining users who have not yet churned.", "내 파일로 여기서 하는 확인은 묶음별 합계입니다. 생존곡선은 도구에서 계산합니다.", "The inline check with your file shows group totals. The survival curve is calculated in the tool."),
  "weekly-marketing-report-template": C("주간 보고서 샘플 열기", "Open a weekly report example", "주간 보고서에 넣을 비용·설치 변화와 다음 주 재검토 근거를 확인합니다.", "Inspect spend and install changes for a weekly report and evidence to revisit next week."),
  "cac-payback-period": C("획득 비용 비교해 보기", "Compare acquisition costs", "획득 단가가 오른 상황을 먼저 읽고, 구매 고객 CAC에 필요한 데이터를 구분합니다.", "Read an acquisition-cost change, then distinguish the data needed for customer CAC.", "설치당 비용 예시입니다. 구매 고객 CAC와 회수 기간은 별도 데이터가 필요합니다.", "This example uses cost per install. Customer CAC and payback need separate data."),
  "marketing-report-sheets-bigquery": C("정리한 데이터로 보고서 보기", "See a report from prepared data", "정리한 캠페인 데이터가 기간 비교와 채널별 비용 변화로 어떻게 이어지는지 확인합니다.", "See how prepared campaign data becomes period comparisons and channel cost changes."),
  "ab-testing": C("A/B 테스트 결과 읽어보기", "Read an A/B test result", "실험군·대조군의 전환율 차이와 불확실성을 함께 읽는 예시입니다.", "Read conversion-rate differences between test and control alongside uncertainty."),
  "ad-creative-testing": C("소재별 성과 비교해 보기", "Compare creative performance", "소재를 더 만들기 전에 현재 소재의 성과 차이와 피로 신호를 확인합니다.", "Inspect performance differences and fatigue signals before making more creatives.", "테스트 개수를 자동으로 정하지 않습니다. 집행한 소재의 성과와 피로 신호를 보는 예시입니다.", "This example compares delivered creatives and fatigue signals; it does not choose your test size."),
  "ad-machine-learning": C("성과가 달라진 채널 찾기", "Find which channel changed", "학습 상태만 보고 판단하기 전에, 비용 변화가 어느 채널에서 나왔는지 살펴봅니다.", "Inspect which channels contributed to a cost change before judging by learning status alone."),
  "ad-performance-diagnosis": C("비용 상승을 채널별로 나눠보기", "Break down a cost increase", "전체 단가 상승을 채널별로 나눠 다음에 점검할 범위를 좁힙니다.", "Split a unit-cost increase by channel to narrow the next investigation."),
  "aha-event-ad-optimization": C("전환과 함께 나타난 행동 찾기", "Explore behaviors linked to conversion", "전환한 사용자에게 함께 나타난 행동 후보와 관측 조건을 확인합니다.", "Inspect behavior candidates associated with conversion and their observation conditions."),
  "aha-moment-retention": C("핵심 행동 후보 비교해 보기", "Compare candidate key behaviors", "핵심 행동 후보별 차이를 살펴보고, 관측 기간이 맞는지 확인합니다.", "Compare candidate key behaviors and check whether observation windows align."),
  "apple-search-ads-guide": C("검색어 조정 후보 살펴보기", "Inspect search-term candidates", "검색어별 탭·설치·비용을 읽고, 조정 후보가 나오는 조건을 확인합니다.", "Read taps, installs and spend by search term and the conditions behind adjustment candidates.", "전환 집계가 끝났는지 확인하기 전에는 조정을 보류합니다.", "Adjustment recommendations stay on hold until conversion maturity is confirmed."),
  "asa-keyword-expansion": C("확장할 검색어 후보 살펴보기", "Explore keyword expansion candidates", "검색어 실적을 바탕으로 Exact 승격·제외를 검토할 후보를 살펴봅니다.", "Inspect search-term performance for Exact-promotion and exclusion candidates."),
  "aso-basics-guide": C("스토어 전환 하락 나눠보기", "Break down a store conversion drop", "전체 스토어 전환율 하락이 유입 구성 때문인지 소스별 변화 때문인지 나눠 봅니다.", "Separate a store conversion drop into traffic composition and source-level changes."),
  "audience-broad-vs-narrow": C("두 타겟의 차이 비교해 보기", "Compare two audience results", "두 집단의 전환율 차이와 표본의 불확실성을 함께 비교합니다.", "Compare conversion-rate differences between two groups alongside sample uncertainty."),
  "brand-campaign-lift": C("캠페인 전후 변화 살펴보기", "Inspect a campaign's before and after", "브랜드 캠페인 집행 전후 추세와 미집행 시 추정 성과를 비교합니다.", "Compare campaign trends with the estimated outcome without the brand campaign."),
  "budget-marginal-efficiency": C("예산 배분 샘플 열기", "Open a budget allocation example", "채널별 추가 지출의 효율을 읽고, 배분안을 검토할 근거를 확인합니다.", "Inspect marginal spending efficiency and evidence for reviewing a budget allocation.", "아래 그림은 배분 전 포화 점검입니다. 샘플에서는 채널별 배분안을 확인합니다.", "The preview checks saturation before allocation. The example opens channel budget recommendations."),
  "budget-scaling-limit": C("증액 판단이 보류되는 예시 보기", "See why a scaling decision is withheld", "관측 행이 있어도 증액 판단을 내릴 수 없는 사례와 부족한 조건을 확인합니다.", "Inspect a case where observed rows still cannot support a scaling decision."),
  "campaign-anomaly-detection": C("성과가 바뀐 구간 살펴보기", "Inspect a performance change", "성과 변화에 크게 기여한 채널을 먼저 찾아 점검 순서를 정합니다.", "Find channels contributing most to a performance change to prioritize investigation."),
  "cannibalization-organic-paid": C("광고·자연 유입 함께 비교하기", "Compare paid and organic traffic", "광고 유입과 자연 유입의 추세를 함께 읽어 잠식 가설을 점검할 출발점을 찾습니다.", "Read paid and organic trends together as a starting point for investigating cannibalization."),
  "cohort-analysis-guide": C("기간별 성과 비교해 보기", "Compare performance across periods", "코호트를 나누기 전, 같은 기간의 지출·설치 변화를 먼저 비교하는 예시입니다.", "Compare spend and installs over matching periods before moving to a cohort analysis.", "첫 화면은 기간별 운영 지표입니다. 코호트 해석에는 사용자별 관측 기간을 맞춰야 합니다.", "The first view compares operating metrics. Cohort interpretation needs aligned user observation windows."),
  "content-element-analysis": C("성과와 관련된 소재 요소 찾기", "Explore elements linked to performance", "소재 요소와 성과의 관련성을 읽고 다음 실험에서 확인할 후보를 찾습니다.", "Read associations between creative elements and performance to select candidates for a later test."),
  "correlation-vs-causation": C("대조군이 있는 결과 읽어보기", "Read a result with a control group", "대조군이 있는 비교에서 관측 변화와 증분 추정의 차이를 살펴봅니다.", "Inspect the difference between observed changes and an incremental estimate with a control group."),
  "cpi-cpa-cpm-difference": C("비용·클릭·설치 함께 보기", "Compare spend, clicks and installs", "지출·노출·클릭·설치를 함께 보고 단가의 분모가 무엇인지 확인합니다.", "Read spend, impressions, clicks and installs together to check each cost metric’s denominator."),
  "creative-attribute-regression": C("소재 요소별 차이 살펴보기", "Inspect creative attribute differences", "소재 속성별 성과 차이를 살펴보되, 관련성을 인과효과와 구분합니다.", "Inspect performance differences by creative attribute while distinguishing association from causation."),
  "funnel-dropoff-analysis": C("단계별 건수 비교해 보기", "Compare funnel stage counts", "노출·클릭·설치 단계의 집계 건수를 비교해 먼저 확인할 단계를 찾습니다.", "Compare aggregate impression, click and install counts to choose a stage to investigate."),
  "google-uac-optimization": C("교체를 검토할 소재 살펴보기", "Inspect creatives worth reviewing", "소재별 성과와 피로 신호를 읽고 교체를 검토할 소재를 살펴봅니다.", "Read creative performance and fatigue signals to inspect candidates for replacement."),
  "hook-3-seconds-framework": C("소재별 반응 비교해 보기", "Compare responses across creatives", "훅을 바꾼 뒤 비교할 클릭·전환 성과를 소재별로 살펴보는 예시입니다.", "Inspect creative-level clicks and conversions to compare after changing a hook.", "클릭·전환 예시입니다. 첫 3초의 시청 이탈을 직접 측정한 결과는 아닙니다.", "This example uses clicks and conversions, not measured drop-off in the first three seconds."),
  "incrementality-measurement": C("대조군과 증분 결과 비교하기", "Compare an incrementality result", "대조군 비교로 추정한 증분과 그 불확실성을 함께 읽습니다.", "Read an incrementality estimate from a control-group comparison alongside uncertainty."),
  "ltv-cac-ratio": C("획득 지표부터 비교해 보기", "Start with acquisition metrics", "LTV/CAC 해석에 앞서 획득 단가의 변화와 필요한 매출 데이터를 구분합니다.", "Inspect acquisition-cost changes and distinguish the revenue data needed to interpret LTV/CAC.", "설치 기준 운영 지표 예시입니다. 실제 LTV/CAC에는 고객 매출과 획득 비용이 필요합니다.", "This example uses install-based metrics. Actual LTV/CAC needs customer revenue and acquisition costs."),
  "marketing-mix-modeling": C("채널 기여도 샘플 열기", "Open a channel contribution example", "채널 기여도를 읽기 전에 함께 움직이는 지출과 식별 한계를 확인합니다.", "Check channels that spend together and identification limits before reading contributions.", "아래 그림은 MMM 전 공선성 점검입니다. 샘플 결과에서도 식별 조건을 함께 확인하세요.", "The preview checks collinearity before MMM. Inspect identification limits in the example result."),
  "meta-advantage-plus-guide": C("소재 성과와 피로 신호 보기", "Inspect creative performance and fatigue", "자동화 캠페인에서도 직접 점검할 소재별 성과와 피로 신호를 확인합니다.", "Inspect creative performance and fatigue signals that still need review in automated campaigns."),
  "multicollinearity-mmm-guide": C("함께 움직이는 채널 찾기", "Find channels that move together", "채널 지출이 함께 움직여 기여도를 나누기 어려운 조합을 찾습니다.", "Find channel-spend combinations that make separate contributions hard to identify."),
  "offline-ad-online-impact": C("집행 전후 변화 비교해 보기", "Compare changes around a campaign", "오프라인 집행 전후의 온라인 성과를 추세와 함께 비교합니다.", "Compare online outcomes around offline campaign dates alongside their trend."),
  "performance-marketer-skills": C("실무 분석 한 번 해보기", "Try an operating analysis", "지출과 성과를 함께 읽고 다음 점검 질문을 정하는 실무 분석을 체험합니다.", "Practice reading spend and outcomes together to decide what to inspect next."),
  "performance-marketing-analysis-order": C("운영 지표부터 살펴보기", "Start with operating metrics", "전체 운영 지표의 변화를 먼저 읽고 원인 점검으로 이어갈 출발점을 찾습니다.", "Read changes in overall operating metrics as a starting point for investigating causes."),
  "performance-marketing-metrics": C("지출부터 전환까지 함께 보기", "Follow spend through to conversion", "지출·노출·클릭·설치의 변화를 함께 비교해 단가 변화의 근거를 읽습니다.", "Compare spend, impressions, clicks and installs to read the evidence behind a unit-cost change."),
  "retargeting-reengagement-guide": C("추가 지출의 효율 살펴보기", "Inspect the efficiency of extra spend", "재타겟팅 증액 전에 평균 단가와 추가 지출의 효율을 비교합니다.", "Compare average cost and marginal spending efficiency before scaling retargeting."),
  "roas-improvement": C("예산을 옮길 채널 살펴보기", "Explore where to move budget", "매출 수익률을 판단하기 전, 추가 지출의 효율과 예산 이동 후보를 살펴봅니다.", "Inspect marginal spending efficiency and budget-move candidates before judging revenue returns.", "설치 기준 포화 점검과 예산 배분 예시입니다. ROAS 판단에는 매출 데이터가 필요합니다.", "The preview checks saturation; the sample opens allocation using installs. Judging ROAS requires revenue data."),
  "store-conversion-drop-diagnosis": C("유입 구성과 전환 변화 나눠보기", "Separate traffic mix and conversion changes", "스토어 전체 전환율 변화를 유입 구성과 소스별 전환 변화로 나눕니다.", "Split an overall store conversion change into traffic mix and source-level conversion changes."),
  "store-listing-experiment": C("스토어 A/B 결과 비교해 보기", "Compare a store A/B result", "스토어 실험의 두 집단 전환율 차이와 불확실성을 함께 읽습니다.", "Read conversion-rate differences between store experiment groups alongside uncertainty."),
  "uplift-holdout-guide": C("홀드아웃 결과 읽어보기", "Read a holdout result", "광고를 받은 집단과 홀드아웃의 차이로 증분을 읽는 예시입니다.", "Read incremental outcomes from the difference between exposed and holdout groups."),
};

export function blogConversionFor(slug, locale = "ko") {
  return BLOG_CONVERSION[slug]?.[locale === "en" ? "en" : "ko"] || null;
}

export const blogExampleFormId = slug => `blog-example-${slug}`;
