// 블로그의 "짧은 답"·적용 범위·검토 정보를 원고와 분리한 편집 레지스트리.
// 검색 메타와 CTA를 섞지 않고, SSR 본문과 JSON-LD가 동일한 답변을 쓰게 한다.
const KO_ANSWERS = {
  "ab-testing": "A/B 테스트는 사전에 정한 표본·관찰 기간·종료 규칙에 따라 효과 크기와 신뢰구간을 함께 판단합니다. p값은 차이가 없다는 가정 아래 관측값 이상으로 극단적인 결과가 나올 확률이며, B가 이길 확률이 아닙니다. 유의해 보이는 순간에 종료하면 고정 표본 검정의 오류율이 달라집니다.",
  "ad-creative-specs-guide": "소재가 반려되거나 크롭되는 이유는 대개 매체별 비율(1:1·9:16 등)·최소 해상도·용량 제한이 서로 다르기 때문입니다. 하나의 파일로 통일하지 말고 집행 전에 매체별 규격과 실제 미리보기를 함께 확인하세요.",
  "ad-creative-testing": "동시에 돌릴 광고 소재 수는 '한 번에 3개'처럼 고정할 수 없고, 테스트 배치 예산을 소재당 판정 예산으로 나눈 뒤 소수점을 버려 정합니다. 이 값은 운영 가능한 슬롯 수이지 통계적 표본 크기가 아니며, 목적도 이번 주 CTR 1등 찾기가 아닙니다.",
  "ad-machine-learning": "광고 머신러닝 학습은 캠페인의 조건에서 성과를 탐색하는 과정입니다. 완료 기준은 매체·목표별로 확인하고, 특정 전환 수나 설정 변경만으로 안정화·초기화를 단정하지 마세요. 변경 이력·추적 상태·성숙 전환을 함께 비교하세요.",
  "ad-performance-diagnosis": "광고 성과가 하락하면 소재부터 갈지 말고 집계 기준 → 전환량 → 트래픽 품질 → 소재 순으로 좁히세요. CPA 상승은 CPM이 올랐거나 CTR·전환율이 떨어졌거나 비싼 캠페인으로 예산이 쏠린 결과라 원인마다 처방이 정반대입니다. 광고 관리자·GA4·MMP·결제 DB의 집계 정의를 맞춰 비교하면 측정 문제와 성과 변화의 점검 범위를 좁힐 수 있습니다.",
  "adjust-vs-appsflyer": "Adjust와 AppsFlyer 중 하나가 모든 팀에 절대적으로 낫지는 않습니다. 필요한 측정 범위, 연동 매체, 데이터 접근 방식(로그 수준 export 가능 여부), 운영 지원을 실제 요구사항에 맞춰 비교하고, 사양은 계약 전 각 사에 직접 확인하세요.",
  "aha-event-ad-optimization": "광고 최적화 이벤트를 설치로 두면, 10초 뒤 이탈한 유저와 핵심 기능을 쓰고 돌아온 유저가 똑같이 설치 1건으로 잡힙니다. 설치 CPA는 낮은데 Aha Event 도달률과 D7 리텐션이 같이 낮다면, 그건 싸게 유저를 산 게 아니라 싸게 이탈을 산 것입니다.",
  "aha-moment-retention": "Aha Moment는 '가입 후 3일 안에 친구 3명 추가'처럼 시점과 횟수를 함께 정한 초기 행동 후보이지, 하나의 정답이 아닙니다. 리텐션과 함께 나타났다는 것만으로 원인이라 볼 수 없고(원래 의지가 높은 유저였을 수 있음), 온보딩으로 유도해 실제로 리텐션이 움직이는지 검증해야 합니다.",
  "ai-era-marketer": "AI가 소재를 100개 뽑아줘도 방향이 틀리면 100개가 다 쓸모없습니다. 목표 정의, 데이터 검증, 인과 해석, 실험 설계처럼 '무엇을 만들지와 결과를 어떻게 믿을지'를 정하는 판단은 여전히 마케터 몫입니다.",
  "apple-search-ads-guide": "Apple Search Ads(ASA) 키워드 최적화는 검색어 리포트에서 시작합니다 — 충분한 탭·설치와 목표 CPA를 함께 충족한 비-Exact 검색어를 Exact 후보로 올리고, 충분히 관찰한 저성과 검색어는 제외 후보로 검토하세요. 성숙도·표본이 부족하면 보류하세요. 예산을 덜 쓰면서 성과가 좋으면 CPT를 조금 높이고, 많이 쓰면서 성과가 나쁘면 낮춥니다.",
  "asa-keyword-expansion": "ASA 키워드 확장은 Discovery로 검색어를 발굴한 뒤, 판단할 만큼 전환이 쌓이면서 목표 CPA도 만족한 검색어만 Exact로 승격하는 과정입니다. 전환 성숙도도 확인하고, 승격한 검색어는 Discovery의 정확 일치 네거티브로 추가해 탐색 범위를 분리하세요. 중복만으로 CPT 상승 원인을 단정할 수는 없습니다.",
  "store-conversion-drop-diagnosis": "앱스토어 전환율이 하락하면 스크린샷 변경에 앞서 유입 믹스를 확인하세요. Search 45%·Browse 9%가 각각 그대로여도 조회 비중이 4,300·2,400에서 2,600·5,200으로 뒤집히면 전체 전환율은 32.1%에서 21.0%로 약 11.1%p 떨어집니다. 소스별 전환율이 그대로인지부터 확인하세요.",
  "store-listing-experiment": "앱스토어 A/B 테스트가 필요한 이유는, 스크린샷 변경 효과를 전후 비교로 재면 같은 기간의 광고 증액·시즌이 전부 그 몫으로 잡히기 때문입니다. 애플 PPO는 원본 외 최대 3개 안을 최대 90일까지 같은 시점 트래픽을 무작위로 갈라 비교하므로 혼입을 줄입니다. 실제 배정과 측정도 확인해야 합니다. 종료 조건은 반드시 시작 전에 정하세요.",
  "aso-basics-guide": "ASO(앱스토어 최적화)는 광고비보다 먼저 손대야 하는 곱셈 항입니다 — 스토어 페이지 조회 10,000건에서 전환율이 30%면 설치 3,000건이지만 40%로 올리면 4,000건이 되어, 같은 광고비로 설치가 33% 늘고 CPI는 25% 내려갑니다. 제품 페이지 조회는 많은데 전환이 낮으면 스크린샷·아이콘·평점을, 노출 자체가 적으면 키워드·제목을 먼저 보세요.",
  "attribution-data-mismatch": "어트리뷰션 데이터 불일치는 귀속 창·집계 시점·전환 정의 차이나 연동 오류에서 생길 수 있습니다. 같은 주 전환이 메타 120건, GA4 70건, MMP 85건, 결제 DB 100건이라면 먼저 정의를 맞추고 누락·중복을 점검하세요.",
  "audience-broad-vs-narrow": "브로드 타겟과 좁은 타겟은 도달·빈도·전환 신호·한계 효율로 비교하세요. 좁힌다고 전환율이 반드시 오르거나 넓힌다고 CPM이 반드시 내려가지는 않습니다. 같은 기간과 성숙 기준으로 비교하고 빈도 상승만으로 피로를 확정하지 마세요.",
  "brand-campaign-lift": "브랜드 캠페인은 직접 클릭 외에 브랜드 검색·직접 유입의 시계열 변화도 확인합니다. 충분한 집행 전 관측으로 기준선을 만들고 자기상관을 반영한 구간과 함께 읽되, 8주는 예시이며 필요한 기간은 계절성과 설계에 따라 달라집니다. 동시 변경을 분리하지 못하면 캠페인의 인과 효과로 확정하지 않습니다.",
  "budget-marginal-efficiency": "마케팅 예산 배분은 평균 ROAS나 CPA가 아니라 다음 1원의 한계 효율로 판단합니다. 모든 계정에 통하는 20~30% 고정 증액 규칙은 없고, 다음 1원의 ROAS가 목표선 위인 채널부터 배분을 검토하는 것이 순서입니다.",
  "budget-scaling-limit": "광고 예산 증액은 평균 CPA가 아니라 한계 CPA로 판단합니다 — 평균은 과거 성적표고 한계는 다음 1원의 가격표입니다. 포화지수(한계 CPA ÷ 평균 CPA)가 1보다 크게 높으면 증액분이 그만큼 안 나오고, 지출이 거의 일정했던 채널은 곡선을 못 그려 판정 자체가 보류됩니다.",
  "campaign-anomaly-detection": "캠페인 이상탐지는 'CPA가 20% 올랐다'가 아니라 '평소 변동폭을 넘어섰다'에만 반응하도록 기준을 잡아야 알림이 쓸모 있어집니다. 이상이 잡히면 숫자가 변한 사실보다 무엇이 변했는지를 기간·전환량·비용·믹스로 분해해야 원인이 나옵니다.",
  "cannibalization-organic-paid": "카니발라이제이션은 유료 광고가 원래 오가닉으로 왔을 유입을 대신 가져가는 현상입니다. 다른 조건이 같고 적절한 설계로 확인했다는 가정에서 유료 100건 감소·오가닉 70건 증가라면 순증분은 30건, iCPA는 보고 CPA의 약 3.33배입니다. 전후 차이만으로 확정하지 마세요.",
  "cohort-analysis-guide": "D7 리텐션은 코호트 시작일로부터 최소 7일이 지난 유저만 넣어 계산해야 합니다. 데이터 최대 날짜가 7월 30일이면 D7은 7월 23일 코호트까지, D30은 6월 30일 코호트까지만 볼 수 있고, 덜 익은 코호트를 0으로 섞으면 최근 코호트가 급락한 것처럼 보입니다.",
  "content-element-analysis": "광고 소재 성과 분석은 후킹·길이·형식을 0/1이나 숫자 열로 만들어 한 번에 비교하는 방법입니다. 요소들이 늘 같이 움직였다면 하나씩 봐서는 구분되지 않고, 종속변수가 CTR 같은 비율인지 조회수 같은 건수인지에 따라 맞는 모형도 달라집니다.",
  "correlation-vs-causation": "상관관계는 두 지표가 함께 움직였다는 관찰이고, 인과관계는 한쪽이 다른 쪽을 만들었다는 주장입니다. 둘을 가르는 가장 흔한 함정은 시즌·프로모션·가격 변동처럼 둘 다를 움직인 제3의 원인이므로, 대조군이나 무작위 실험처럼 다른 설명을 줄이는 설계가 있어야 인과를 말할 수 있습니다.",
  "cpi-cpa-cpm-difference": "CPM은 노출 1,000회당, CPC는 클릭당, CPI는 설치당, CPA는 목표 행동당 비용입니다. CTR을 비율로 넣으면 CPC = CPM ÷ (1,000 × CTR)이므로 CPM 2,000원·CTR 1%(0.01)의 CPC는 200원입니다. 같은 집계 범위에서 노출 단가와 클릭 반응을 나눠 보되, 분해만으로 경매나 소재를 원인으로 확정하지 마세요.",
  "creative-attribute-regression": "광고 소재 회귀분석은 집행한 소재의 속성을 사실 기반 0/1·숫자 열로 만들어 연관성을 비교합니다. 신뢰구간이 기준값(차이는 0, 비율은 1)을 걸치면 효과 없음이 아니라 불확실로 읽으세요. 반복 소재와 시간 순서를 검증에 반영해야 합니다.",
  "event-taxonomy-guide": "이벤트 택소노미는 행동을 이벤트 이름으로, 맥락을 파라미터로 분리해야 GA4·MMP·광고 매체·내부 리포트가 같은 행동을 같은 뜻으로 읽습니다. 새로 이름을 만들기 전에 GA4 권장 이벤트를 먼저 확인하고, 제품 정의와 맞을 때는 그대로 쓰세요.",
  "funnel-dropoff-analysis": "전환율 개선은 퍼널 단계별 분모와 기간을 맞추는 데서 시작합니다. 설치자의 25%가 가입했다면 75%는 관찰 기간 내 가입이 확인되지 않은 것이지 반드시 이탈한 것은 아닙니다. 개선 여지·트래픽·후속 가치·실행 비용으로 우선순위를 정하세요.",
  "ga4-data-traps": "GA4 숫자가 다른 건 대부분 고장이 아니라 집계 기준 차이입니다 — 세션 정의, 처리 지연, 개인정보 보호 임계값, 귀속 모델이 다른 도구와 다르기 때문입니다. 설정을 고치기 전에 비교할 범위와 기준을 먼저 맞추면, 귀속 차이를 버그로 오해해 불필요한 세팅을 건드리는 일을 막을 수 있습니다.",
  "google-uac-optimization": "Google UAC의 주요 레버는 입찰 목표·에셋·전환 이벤트입니다. 지원하는 제외 설정도 확인하세요. 설치·행동·매출은 필수 승급 순서가 아니며, 주당 변경 횟수만으로 학습 장애를 판정할 수 없습니다.",
  "hook-3-seconds-framework": "영상 광고의 초반 반응을 확인하고 첫 몇 초 안에 메시지의 관련성을 전달하세요. 모든 이탈이 3초 안에 일어나는 것은 아닙니다. 다만 모든 소재에 같은 후킹 공식이 통하지는 않으니, 타깃의 문제·메시지·형식을 바꾼 소재를 실제 이탈률로 비교해 검증하세요.",
  "incrementality-measurement": "증분성(인크리멘탈리티) 측정은 리포트에 찍힌 전환이 아니라 광고가 없었다면 사라졌을 전환을 재는 일입니다 — 마케팅 전환 500건 중 실제 증분은 120건이고 나머지 380건은 원래 올 손님이었을 수 있습니다. ROAS 800%가 찍혀도 증분이 낮으면 증액 근거가 되지 않으므로, 적절히 설계한 무작위 홀드아웃과 불확실성으로 확인할 수 있습니다.",
  "ios-att-skan-guide": "iOS 성과 차이는 ATT 동의율만으로 설명할 수 없습니다. ATT는 IDFA 기반 교차 앱 추적을 제한하며 모든 측정을 막지는 않습니다. SKAN 4는 0~2일·3~7일·8~35일 창에서 조건에 따라 최대 세 포스트백을 보내고 수신에는 추가 지연이 있습니다.",
  "ltv-cac-ratio": "LTV:CAC는 3:1이 흔한 기준선이지만, 그 비율을 보기 전에 계산이 맞는지부터 확인해야 합니다. 결제 고객 획득에 5,000만 원을 써서 500명을 데려왔다면 CAC는 10만 원이고, 이들이 월 2만 원씩 평균 12개월 남으면 LTV는 24만 원이라 2.4:1인데, 분모에 무엇을 넣었는지(광고비만인지 인건비 포함인지)에 따라 이 값이 통째로 달라집니다.",
  "marketing-mix-modeling": "MMM(마케팅 믹스 모델링)은 주별 채널 지출과 매출을 놓고 '매출 = 베이스라인 + 채널별 기여 + 외부요인'을 추정하는 방법입니다. 점 추정과 함께 실제 구간의 종류·수준·시간순 검증을 확인해야 하며, 관측 데이터 기반이라 연관이지 인과가 아닙니다.",
  "multicollinearity-mmm-guide": "MMM에서 특정 채널 기여도가 음수로 나오면 모델 고장보다 다중공선성을 먼저 의심하세요. 검색과 소셜 예산을 늘 같이 올리고 내렸다면 모델은 둘 중 누가 결과를 만들었는지 구분할 근거가 없고, 이때 VIF가 높게 나오는 것은 '효과가 없다'가 아니라 '이 데이터로는 분리할 수 없다'는 뜻입니다.",
  "meta-advantage-plus-guide": "Meta Advantage+ App은 OS별 측정, 최적화 이벤트·가치 데이터, 입찰 목표를 함께 점검하세요. 현재 캠페인의 지원 요건과 클릭·조회 귀속 창을 확인하고, 과거 웹 AEM 제한을 앱당 8개라는 공통 규칙으로 적용하지 마세요.",
  "offline-ad-online-impact": "TV·옥외 광고는 브랜드 검색량·직접 유입의 장기 추세와 방영 전후 단기 변화를 함께 확인합니다. 8주 기준선이나 방영 후 15~60분은 분석 예시이며 충분한 기간을 보장하지 않습니다. 디지털 예산 등 동시 변경을 기록하고, 비교 설계로 분리하지 못하면 오프라인 광고의 인과 효과로 확정하지 않습니다.",
  "performance-marketer-skills": "퍼포먼스 마케터에게 필요한 건 툴 암기가 아니라 문제 정의·데이터 품질 확인·실험 설계·결과 해석 순서입니다. 실무에서는 스프레드시트를 제대로 쓰는 것부터 시작하고, 매체 광고 관리자는 하나만 손에 익혀도 충분합니다.",
  "performance-marketing-analysis-order": "퍼포먼스 마케팅 분석은 분석 이름부터 고르지 말고, 지금 답해야 할 질문과 가진 데이터의 단위부터 확인하세요. 일별 성과는 대시보드와 변동 분해, 지출 변화가 충분하면 포화도와 예산 배분, 대조군이 있으면 증분 분석, 52주 이상 채널 패널이 있으면 VIF를 거쳐 MMM으로 이어가는 순서가 안전합니다.",
  "performance-marketing-metrics": "퍼포먼스 마케팅 지표는 지출 → CPI → CPA → ROAS → LTV:CAC를 연결해 점검할 단계를 좁히세요. 5,000만 원으로 설치 5,000건이면 CPI 1만 원이고, 같은 지출의 매출이 1.5억 원이면 ROAS 300%입니다. 낮은 CPA와 낮은 ROAS는 객단가뿐 아니라 전환 정의·매출 창·유입 구성·추적 누락도 확인해야 하는 신호입니다.",
  "postback-integration-guide": "포스트백 연동은 앱→MMP→매체에서 마지막으로 정상 확인된 지점부터 점검하세요. SAN은 귀속 방식, S2S는 전송 방식이므로 양자택일이 아닙니다. 앱 ID·파트너 설정·이벤트 매핑·인증·중복 제거를 순서대로 대조하세요.",
  "retargeting-reengagement-guide": "리타겟팅과 신규 획득은 목적과 대상이 달라 분리해서 평가하세요. 전환 수가 각각 100건이면 CPA 30,000원과 6,000원의 전체 CPA는 18,000원이지만 신규 획득 단가는 아닙니다. 증분은 검정력·기간을 정한 무작위 홀드아웃과 불확실성으로 확인하세요.",
  "roas-improvement": "ROAS 하락의 원인은 예산이 아니라 대개 그 앞에 있습니다 — 통합 ROAS 300%가 전혀 다른 채널별 성적을 덮고 있을 수 있기 때문입니다. 예산을 줄이기 전에 데이터 성숙도·채널별 효율·전환 이후 객단가를 갈라 보고, ROAS 개선은 지금 좋아 보이는 채널에 몰아주는 게 아니라 다음 1원이 더 잘 도는 곳으로 옮기는 것으로 합니다.",
  "uplift-holdout-guide": "광고 업리프트 측정은 광고 배정군과 홀드아웃 배정군의 전환율 차이를 추정합니다. 실제 노출자만 골라 비교하면 배정이 깨질 수 있습니다. 배정군 8%, 홀드아웃 5%면 차이는 3%p입니다. 무작위 배정이 아니거나 두 그룹의 기간·대상이 다르면 이 차이를 광고 효과로 볼 수 없고, 구간이 0을 걸치면 '효과 없음'이 아니라 '아직 구분 안 됨'으로 읽어야 합니다.",
  "skan4-migration-guide": "SKAN 4 전환은 구매 지연과 창별로 필요한 판단부터 정하세요. fine 값은 첫 창, 뒤 두 창은 coarse 값만 지원합니다. 늦은 행동이 핵심이면 창 2·3을 초기 설계에 포함하고, 캠페인 통합은 통제 손실과 실제 반환 정보량을 비교해 결정하세요.",
  "skan-conversion-value-schema": "SKAN 컨버전 밸류의 fine 값은 0~63이며 SKAN 4 첫 창에서만 받을 수 있습니다. 하루 500건을 64칸에 균등 배분하면 약 7.8건이지만 실제 분포와 누락은 다릅니다. 빈 칸 수만으로 실패를 판정하지 말고 행동 가치·볼륨·반환 조건으로 스키마를 정하세요.",
  "skan-vs-mmp-attribution": "SKAN 어트리뷰션과 MMP 숫자는 귀속 방식·집계일·지연에 따라 다를 수 있으며 연동 오류도 점검해야 합니다. MMP도 SKAN을 수신하므로 두 이름은 배타적 소스가 아닙니다. 같은 성숙 기간과 정의로 비교하고 격차를 미관측 설치 수로 해석하지 마세요.",
};

const EN_ANSWERS = {
  "ab-testing": "A/B testing uses a preplanned sample, observation window, and stopping rules, alongside effect size and confidence intervals. A p-value is conditional on the no-difference hypothesis, not the probability that B wins. Stopping when significance first appears changes a fixed-sample test’s error rate.",
  "ad-creative-specs-guide": "Creatives get rejected or cropped because aspect ratios (1:1, 9:16), minimum resolutions, and file-size caps differ by platform. Do not ship one universal file — check each platform's spec and an actual preview before launch.",
  "ad-creative-testing": "Ad creative testing cannot fix the number at 'three at a time'; divide the test batch budget by the per-creative decision budget and round down. That result is how many operational slots you have, not a statistical sample size, and the goal is not to crown this week's CTR winner.",
  "ad-machine-learning": "The ad learning phase explores performance under campaign conditions. Check criteria for the platform and goal; neither a fixed event count nor an edit alone proves stabilization or a reset. Compare change history, tracking and mature conversions.",
  "ad-performance-diagnosis": "When ad performance drops, do not swap creative first — narrow in this order: measurement setup, conversion volume, traffic quality, then creative. A rising CPA is the result of a higher CPM, a falling CTR or conversion rate, or budget drifting toward expensive campaigns, and each of those has a different fix. Comparing conversion counts across the ads manager, GA4, your MMP, and the payment database separates a tracking problem from a real performance problem in one step.",
  "adjust-vs-appsflyer": "Neither Adjust nor AppsFlyer is absolutely better for every team. Compare them against your actual requirements — measurement scope, network integrations, data access such as log-level export, and support — and confirm specifications with each vendor before signing.",
  "aha-event-ad-optimization": "Ad optimization events decide what the algorithm buys: leave it on installs and a user who leaves after 10 seconds counts the same as one who uses a core feature and returns days later. When install CPA is low while Aha-event reach and D7 retention are also low, you did not buy users cheaply — you bought churn cheaply.",
  "aha-moment-retention": "An Aha moment is a candidate early action defined with both timing and count — 'added 3 friends within 3 days of signup' — not a single truth. Appearing alongside high retention does not make it causal (motivated users add more friends anyway), so drive it in onboarding and check whether retention actually moves.",
  "ai-era-marketer": "AI can produce 100 creatives, and all 100 are wasted if the direction is wrong. Defining the objective, validating the data, reading causation, and designing experiments — deciding what to make and whether to believe the result — still belong to the marketer.",
  "apple-search-ads-guide": "Apple Search Ads (ASA) keyword optimization starts in the search terms report: promote non-Exact terms only after they have enough taps and installs and meet target CPA, and review sufficiently observed poor performers as negative candidates. Hold terms with immature or insufficient data. Raise CPT slightly when pacing is low and performance is good; lower it when spend is high and performance misses target.",
  "asa-keyword-expansion": "ASA keyword expansion means using Discovery to find search terms, then promoting to Exact only those with enough conversions to judge on and a CPA inside target. Also verify conversion maturity and add promoted terms as exact-match Discovery negatives to separate exploration. Overlap alone does not explain a CPT increase.",
  "store-conversion-drop-diagnosis": "When store conversion drops, inspect traffic mix before choosing a screenshot experiment. With Search at 45% and Browse at 9% both unchanged, flipping views from 4,300 and 2,400 to 2,600 and 5,200 takes the blended rate from 32.1% to 21.0% \u2014 an approximately 11.1pp fall with no source getting worse. Check whether per-source rates moved before touching the page.",
  "store-listing-experiment": "App Store A/B testing exists because before-and-after credits that window's ad scaling and seasonality to the screenshot you changed. Apple PPO runs up to three treatments alongside the original for up to 90 days, splitting same-moment traffic at random to reduce confounding in expectation; actual allocation and measurement still need checking. Fix the stop condition before launching, not while watching.",
  "aso-basics-guide": "App Store Optimization (ASO) is a multiplier that sits in front of ad spend: at 10,000 product page views, moving conversion from 30% to 40% takes installs from 3,000 to 4,000 — 33% more installs and 25% lower CPI on the same budget. If views are high but installs are not, fix screenshots, icon, and rating; if views themselves are low, fix keywords and title.",
  "attribution-data-mismatch": "Attribution mismatch can reflect windows, timing, conversion definitions or integration errors. If the same week shows 120 Meta conversions, 70 in GA4, 85 in an MMP and 100 in the payment database, align definitions and check missingness and duplicates.",
  "audience-broad-vs-narrow": "Compare broad versus narrow targeting using reach, frequency, conversion signals and marginal efficiency. Narrowing does not guarantee higher conversion, nor broadening cheaper CPM. Match maturity and windows, and do not infer fatigue from frequency alone.",
  "brand-campaign-lift": "Assess brand-search and direct-traffic time series alongside direct clicks. Build a baseline from adequate pre-campaign observations and read the gap with an interval accounting for autocorrelation. Eight weeks is an example, not a universal minimum; seasonality and design determine the required history. Unresolved concurrent changes prevent a causal conclusion.",
  "budget-marginal-efficiency": "Marketing budget allocation decisions belong to the marginal efficiency of the next unit of spend, not to average ROAS or CPA. There is no universal 20–30% step rule; start with channels whose next-dollar ROAS still sits above your target line.",
  "budget-scaling-limit": "Scaling ad budget is a decision about marginal CPA, not average CPA — the average is a report card on the past and the margin is the price tag on the next unit of spend. A saturation index (marginal ÷ average CPA) well above 1 means added budget returns proportionally less, and a channel whose spend barely varied cannot produce a curve at all, so its verdict is withheld.",
  "campaign-anomaly-detection": "Campaign anomaly detection is only useful when alerts fire on 'outside normal variation' rather than on 'CPA rose 20%'. Once one fires, decompose what changed — period, conversion volume, cost, mix — because the fact that a number moved is not yet a cause.",
  "cannibalization-organic-paid": "Cannibalization is paid advertising taking traffic that would otherwise arrive organically. Assuming comparable conditions and a valid design, 100 fewer paid conversions and 70 more organic imply 30 incremental conversions and iCPA about 3.33 times reported CPA. Before–after differences alone do not establish this.",
  "cohort-analysis-guide": "D7 retention must be calculated only from users at least 7 days past their cohort start date. If your data ends July 30, D7 is readable through the July 23 cohort and D30 through the June 30 cohort — mixing immature cohorts in as zeros makes recent cohorts look like a collapse that never happened.",
  "content-element-analysis": "Ad creative performance analysis turns hook, length, and format into 0/1 or numeric columns and compares them in one pass. Elements that always travelled together cannot be separated one at a time, and the right model differs depending on whether the outcome is a rate like CTR or a count like views.",
  "correlation-vs-causation": "Correlation is the observation that two metrics moved together; causation is the claim that one produced the other. The usual culprit between them is a third cause — season, promotion, price change — moving both, so you need a design such as a control group or randomization before claiming cause.",
  "cpi-cpa-cpm-difference": "CPM is cost per 1,000 impressions, CPC per click, CPI per install, and CPA per target action. With CTR as a fraction, CPC = CPM ÷ (1,000 × CTR): CPM $2 and CTR 1% (0.01) give CPC $0.20. Use the same reporting scope and separate impression cost from click response without treating the decomposition as proof of cause.",
  "creative-attribute-regression": "Ad creative regression compares associations using factual attribute columns. An interval crossing its null reference—zero for differences, one for ratios—means uncertainty, not no effect. Account for repeated creatives and time order in validation.",
  "event-taxonomy-guide": "An event taxonomy works when the action is the event name and the context lives in parameters, so GA4, your MMP, ad platforms, and internal reports read the same behavior the same way. Check GA4's recommended events before inventing a name, and use them directly when they fit your product definition.",
  "funnel-dropoff-analysis": "Conversion rate optimization starts with matching funnel denominators and windows. If 25% of installers sign up, the remaining 75% have no observed signup in that window; they have not necessarily left. Prioritize improvement potential, traffic, downstream value and effort.",
  "ga4-data-traps": "GA4 numbers usually differ because of counting rules, not bugs — session definition, processing latency, privacy thresholds, and attribution model all differ from other tools. Align the comparison scope and definitions before changing settings, or you will 'fix' an attribution difference that was never broken.",
  "google-uac-optimization": "Google UAC’s main levers are bidding goals, assets and conversion events; check supported exclusions too. Install, action and value goals are not mandatory stages, and weekly edit counts alone do not establish a learning failure.",
  "hook-3-seconds-framework": "Check early video response and communicate relevance in the opening seconds. Not all drop-off happens within three seconds. No single hook formula fits every creative, though — compare variants that change the audience problem, message, and format against actual drop-off data.",
  "incrementality-measurement": "Incrementality measurement asks not how many conversions your report shows but how many would disappear without the ad — of 500 marketing conversions, only 120 may be incremental while 380 were coming anyway. A reported ROAS of 800% is not a scaling case if lift is low, and a well-designed randomized holdout is one way to assess it.",
  "ios-att-skan-guide": "iOS report differences cannot be explained by ATT consent alone. ATT restricts IDFA-based cross-app tracking, not all measurement. SKAN 4 supports up to three conditional postbacks for days 0–2, 3–7 and 8–35, with additional delivery delay.",
  "ltv-cac-ratio": "LTV:CAC of 3:1 is a common reference line, but check the arithmetic before trusting the ratio. Spending $50,000 to acquire 500 paying customers gives CAC of $100, and if they spend $20 a month for 12 months LTV is $240 — a 2.4:1 ratio that shifts entirely depending on whether the denominator holds media spend alone or headcount too.",
  "marketing-mix-modeling": "Marketing mix modeling (MMM) takes weekly channel spend and revenue and estimates revenue = baseline + per-channel contribution + external factors. Read point estimates alongside the actual interval type, level, and time-ordered validation, and treat it as association from observational data, not causation.",
  "multicollinearity-mmm-guide": "When an MMM channel comes back with a negative coefficient, suspect multicollinearity before assuming the model broke. If search and social budgets always rose and fell together, the model has no basis to separate them, and a high VIF means 'this data cannot separate these channels' — not 'this channel does not work'.",
  "meta-advantage-plus-guide": "For Meta Advantage+ App, check OS measurement, optimization events and value data, and bidding goals together. Verify current campaign requirements and click/view attribution windows; do not apply an old web AEM limit as a universal eight-event-per-app rule.",
  "offline-ad-online-impact": "Assess long-term brand-search and direct-traffic trends alongside short-term changes around TV or out-of-home exposure. An eight-week baseline or a 15–60-minute response window is an example, not a guarantee of adequate observation. Record concurrent digital-budget changes; without a design that separates them, do not attribute the change causally to offline advertising.",
  "performance-marketer-skills": "What a performance marketer needs is not tool memorisation but an order: problem definition, data quality checks, experiment design, then interpretation. In practice spreadsheet fluency carries most of the work, and one ads manager learned properly is enough.",
  "performance-marketing-analysis-order": "Performance marketing analysis starts with the decision and the grain of the data, not the name of a method. Use daily performance for monitoring and variance decomposition, spend variation for saturation and allocation, a control for incrementality, and a 52+ week channel panel with a VIF check before MMM.",
  "performance-marketing-metrics": "Read performance marketing metrics as spend → CPI → CPA → ROAS → LTV:CAC to narrow the stage to investigate. $50,000 for 5,000 installs is a $10 CPI, and $150,000 revenue on that spend is 300% ROAS. Low CPA with low ROAS calls for checking order value, conversion definitions, revenue windows, audience mix, and tracking gaps.",
  "postback-integration-guide": "Debug postback integration from the last verified point in app→MMP→network delivery. SAN describes attribution and S2S describes transport; they are not alternatives. Compare app IDs, partner settings, event mapping, authentication and deduplication.",
  "retargeting-reengagement-guide": "Evaluate retargeting separately from acquisition because goals and audiences differ. At 100 conversions each, $30 and $6 CPA blend to $18, which is not the acquisition CPA. Assess lift using a randomized holdout with preplanned power, duration and uncertainty.",
  "roas-improvement": "When ROAS has dropped, cutting budget first hides the cause, because a blended 300% ROAS can sit on top of very different per-channel results. Separate data maturity, per-channel efficiency, and post-conversion order value first, then reallocate by asking where the next dollar performs better rather than piling into whatever looks best.",
  "uplift-holdout-guide": "Advertising uplift compares the assigned treatment and holdout groups. Selecting only actually exposed users can break randomization. Rates of 8% and 5% imply a 3pp difference. Without random assignment, or when the two groups differ in period or audience, that gap is not ad effect, and an interval crossing zero means 'not yet distinguishable', not 'no effect'.",
  "skan4-migration-guide": "SKAN 4 migration starts with purchase delay and decisions needed per window. Fine values are first-window only; later windows support coarse values. Include windows 2–3 early when late behavior matters, and weigh consolidation against lost control and observed return detail.",
  "skan-conversion-value-schema": "The fine SKAN conversion value is 0–63 and available only in the first SKAN 4 window. Uniformly splitting 500 daily installs across 64 slots averages about 7.8, but actual distribution and missingness differ. Design for decision value, volume and return conditions, not empty-slot count alone.",
  "skan-vs-mmp-attribution": "SKAN attribution and MMP numbers may differ by attribution method, date basis and delay; check integration errors too. An MMP may ingest SKAN, so the names are not exclusive sources. Compare mature periods and definitions; the gap does not estimate unseen installs.",
};

const CONDITION_GROUP_BY_SLUG = {
  "ab-testing": "experiment", "aha-event-ad-optimization": "causal", "aha-moment-retention": "causal",
  "cannibalization-organic-paid": "causal", "correlation-vs-causation": "causal", "incrementality-measurement": "causal",
  "marketing-mix-modeling": "causal", "ad-creative-specs-guide": "platform", "ad-creative-testing": "creative", "ad-machine-learning": "platform",
  "multicollinearity-mmm-guide": "causal",
  "brand-campaign-lift": "causal", "offline-ad-online-impact": "causal", "budget-scaling-limit": "economics",
  "content-element-analysis": "creative", "creative-attribute-regression": "creative", "asa-keyword-expansion": "platform",
  "adjust-vs-appsflyer": "platform", "apple-search-ads-guide": "platform", "aso-basics-guide": "platform",
  "google-uac-optimization": "platform", "ios-att-skan-guide": "platform", "meta-advantage-plus-guide": "platform",
  "postback-integration-guide": "platform", "ad-performance-diagnosis": "measurement", "attribution-data-mismatch": "measurement",
  "campaign-anomaly-detection": "measurement", "cohort-analysis-guide": "measurement", "cpi-cpa-cpm-difference": "measurement",
  "event-taxonomy-guide": "measurement", "funnel-dropoff-analysis": "measurement", "ga4-data-traps": "measurement",
  "performance-marketing-metrics": "measurement", "budget-marginal-efficiency": "economics", "ltv-cac-ratio": "economics",
  "performance-marketing-analysis-order": "measurement",
  "audience-broad-vs-narrow": "creative", "hook-3-seconds-framework": "creative", "retargeting-reengagement-guide": "creative",
  "ai-era-marketer": "editorial", "performance-marketer-skills": "editorial",
  "roas-improvement": "economics",
  "uplift-holdout-guide": "causal",
  "store-conversion-drop-diagnosis": "measurement", "store-listing-experiment": "experiment",
  "skan4-migration-guide": "measurement", "skan-conversion-value-schema": "measurement", "skan-vs-mmp-attribution": "measurement",
};

const CONDITIONS = {
  ko: {
    experiment: "무작위 배정, 사전 종료 기준, 서로 독립인 관측치가 확보된 실험에 적용합니다. 표본이 작거나 중간 결과를 반복 확인했다면 판정을 보수적으로 해석하세요.",
    causal: "관측 데이터의 연관성만으로 인과를 확정할 수 없습니다. 대조군의 비교 가능성, 동시 변화, 표본 규모를 확인하고 중요한 결정은 실험으로 검증하세요.",
    platform: "매체 정책과 제품 기능은 바뀔 수 있습니다. 계정 유형·국가·측정 설정을 확인하고 집행 시점의 공식 문서를 최종 기준으로 사용하세요.",
    measurement: "같은 기간, 시간대, 전환 정의, 집계 단위를 맞춘 비교에 적용합니다. 모수와 누락 데이터를 확인하지 않은 비율 비교는 결론에서 제외하세요.",
    economics: "비용·매출·고객 범위와 관찰 기간을 동일하게 맞춘 데이터에 적용합니다. 미래 효율은 추정치이므로 작은 예산 단계로 검증하세요.",
    creative: "타깃, 지면, 메시지, 노출 빈도가 비슷한 조건의 비교에 적용합니다. 매체 평균보다 실제 계정의 전환량과 소재 실험 결과를 우선하세요.",
    editorial: "팀의 역할과 제품 단계에 따라 우선순위가 달라지는 편집 관점입니다. 채용 요건이나 조직 설계를 위한 보편적 기준으로 단정하지 마세요.",
  },
  en: {
    experiment: "This applies to experiments with random assignment, a pre-set stopping rule, and independent observations. Treat the result conservatively if the sample is small or repeatedly inspected mid-test.",
    causal: "Observational association alone does not establish causality. Check control-group comparability, simultaneous changes, and sample size, then validate consequential decisions with an experiment.",
    platform: "Platform policies and product behavior can change. Check account type, country, and measurement setup, and use the current official documentation as the final operating reference.",
    measurement: "This applies when date range, time zone, conversion definition, and aggregation grain are aligned. Exclude ratio comparisons whose denominator or missingness has not been checked.",
    economics: "Align cost, revenue, customer scope, and observation window. Future efficiency is an estimate, so validate it through small budget steps.",
    creative: "Compare like-for-like audiences, placements, messages, and frequency. Prefer conversion volume and creative-test evidence from the actual account over platform-wide averages.",
    editorial: "This is an editorial perspective whose priorities depend on team role and product stage. Do not treat it as a universal hiring or organization-design standard.",
  },
};

export function getBlogEditorial(locale, slug, source = {}) {
  const lang = locale === "en" ? "en" : "ko";
  const answer = source.answer || (lang === "en" ? EN_ANSWERS[slug] : KO_ANSWERS[slug]) || "";
  const conditionGroup = CONDITION_GROUP_BY_SLUG[slug] || "measurement";
  const conditions = source.conditions || CONDITIONS[lang][conditionGroup];
  return {
    answer,
    conditions,
    // 실제 검토 정보가 원고에 있을 때만 노출한다. 발행일을 검토일로 바꾸지 않는다.
    reviewer: source.reviewer || "",
    reviewedAt: source.reviewedAt || "",
    sources: Array.isArray(source.sources) ? source.sources.filter((item) => item?.title && item?.url) : [],
  };
}

export function publishedEditorialSlugs(locale) {
  return Object.keys(locale === "en" ? EN_ANSWERS : KO_ANSWERS)
    .filter((slug) => slug !== "adjust-vs-appsflyer");
}
