// 블로그의 "짧은 답"·적용 범위·검토 정보를 원고와 분리한 편집 레지스트리.
// 검색 메타와 CTA를 섞지 않고, SSR 본문과 JSON-LD가 동일한 답변을 쓰게 한다.
const KO_ANSWERS = {
  "ab-testing": "A/B 테스트는 전환율 4.2%와 4.8%를 눈으로 비교하는 게 아니라, 그 차이가 우연의 범위를 벗어났는지로 판정합니다. 표본 크기와 종료 시점을 시작 전에 정해두고, 중간에 좋아 보여도 그때 멈추지 마세요 — 3일차에 멈추면 나중에 +0.4%p로 수렴할 차이를 '대승'으로 착각합니다.",
  "ad-creative-specs-guide": "소재가 반려되거나 크롭되는 이유는 대개 매체별 비율(1:1·9:16 등)·최소 해상도·용량 제한이 서로 다르기 때문입니다. 하나의 파일로 통일하지 말고 집행 전에 매체별 규격과 실제 미리보기를 함께 확인하세요.",
  "ad-creative-testing": "동시에 돌릴 광고 소재 수는 '한 번에 3개'처럼 고정할 수 없고, 테스트 배치 예산을 소재당 판정 예산으로 나눈 뒤 소수점을 버려 정합니다. 이 값은 운영 가능한 슬롯 수이지 통계적 표본 크기가 아니며, 목적도 이번 주 CTR 1등 찾기가 아닙니다.",
  "ad-machine-learning": "광고 머신러닝의 학습 단계는 메타 기준 '7일 이내 최적화 이벤트 50건'으로 끝납니다. 그 안에 예산·타겟·소재를 바꾸면 학습이 리셋되므로, 변경은 한 번에 하나씩 하고 학습이 안정될 때까지 평가를 미루세요.",
  "ad-performance-diagnosis": "광고 성과가 하락하면 소재부터 갈지 말고 집계 기준 → 전환량 → 트래픽 품질 → 소재 순으로 좁히세요. 광고 관리자·GA4·MMP·결제 DB의 전환 수가 함께 떨어졌는지 비교하면 측정 문제인지 실제 성과 문제인지가 한 번에 갈립니다.",
  "adjust-vs-appsflyer": "Adjust와 AppsFlyer 중 하나가 모든 팀에 절대적으로 낫지는 않습니다. 필요한 측정 범위, 연동 매체, 데이터 접근 방식(로그 수준 export 가능 여부), 운영 지원을 실제 요구사항에 맞춰 비교하고, 사양은 계약 전 각 사에 직접 확인하세요.",
  "aha-event-ad-optimization": "광고 플랫폼에는 설치 1건으로 똑같이 잡히지만 10초 뒤 이탈한 유저와 핵심 기능을 쓰고 돌아온 유저는 가치가 다릅니다. 설치 CPA는 낮은데 Aha Event 도달률과 D7 리텐션이 같이 낮다면, 그건 싸게 유저를 산 게 아니라 싸게 이탈을 산 것입니다.",
  "aha-moment-retention": "Aha Moment는 '가입 후 3일 안에 친구 3명 추가'처럼 시점과 횟수를 함께 정한 초기 행동 후보이지, 하나의 정답이 아닙니다. 리텐션과 함께 나타났다는 것만으로 원인이라 볼 수 없고(원래 의지가 높은 유저였을 수 있음), 온보딩으로 유도해 실제로 리텐션이 움직이는지 검증해야 합니다.",
  "ai-era-marketer": "AI가 소재를 100개 뽑아줘도 방향이 틀리면 100개가 다 쓸모없습니다. 목표 정의, 데이터 검증, 인과 해석, 실험 설계처럼 '무엇을 만들지와 결과를 어떻게 믿을지'를 정하는 판단은 여전히 마케터 몫입니다.",
  "apple-search-ads-guide": "Apple Search Ads(ASA)에서는 검색어 리포트에서 충분한 탭·설치와 목표 CPA를 함께 충족한 비-Exact 검색어를 Exact 후보로 올리세요. 예산을 덜 쓰면서 성과가 좋으면 CPT를 조금 높이고, 많이 쓰면서 성과가 나쁘면 낮춥니다.",
  "asa-keyword-expansion": "ASA 키워드 확장은 Discovery로 검색어를 발굴한 뒤, 판단할 만큼 전환이 쌓이면서 목표 CPA도 만족한 검색어만 Exact로 승격하는 과정입니다. 전환 2건에 CPA 4천원이라 승격했다가 물량 붙이면 3만원이 되는 일이 흔하니 두 조건을 반드시 함께 보고, 승격한 검색어는 Discovery에 네거티브로 넣어 자기 입찰가를 올리지 마세요.",
  "aso-basics-guide": "ASO는 광고비보다 먼저 손대야 하는 곱셈 항입니다 — 스토어 페이지 조회 10,000건에서 전환율이 30%면 설치 3,000건이지만 40%로 올리면 4,000건이 되어, 같은 광고비로 설치가 33% 늘고 CPI는 25% 내려갑니다. 제품 페이지 조회는 많은데 전환이 낮으면 스크린샷·아이콘·평점을, 노출 자체가 적으면 키워드·제목을 먼저 보세요.",
  "attribution-data-mismatch": "어트리뷰션 데이터 불일치는 흔합니다 — 같은 주 전환이 메타 120건, GA4 70건, MMP 85건, 결제 DB 100건으로 갈리는 식입니다. 어느 하나가 틀린 게 아니라 귀속 창·집계 시점·전환 정의가 서로 다른 것이므로, 숫자를 고르기 전에 각 시스템의 기준을 표로 맞추세요.",
  "audience-broad-vs-narrow": "브로드 타겟과 좁은 타겟 중 정답은 학습에 필요한 전환 신호가 충분한지로 갈립니다. 전환이 얇은 계정에서 타겟을 좁히면 알고리즘이 학습할 데이터가 부족해지고, 반대로 제품이 명확히 특정 층에만 맞는데 넓게 열면 CPA만 오릅니다.",
  "brand-campaign-lift": "브랜드 캠페인은 클릭이 아니라 시계열로 평가합니다. 광고를 본 사람이 며칠 뒤 브랜드명을 직접 검색해 들어오면 그 전환은 브랜드 검색·직접 유입으로 잡히기 때문에, 집행 전 최소 8주 추세를 기준선으로 두고 그 위로 얼마나 벗어났는지를 자기상관을 반영한 구간과 함께 봐야 합니다.",
  "budget-marginal-efficiency": "예산 증액·삭감은 평균 ROAS나 CPA가 아니라 다음 1원의 한계 효율로 판단합니다. 모든 계정에 통하는 20~30% 고정 증액 규칙은 없고, 다음 1원의 ROAS가 목표선 위인 채널부터 검토하는 것이 순서입니다.",
  "budget-scaling-limit": "예산 증액은 평균 CPA가 아니라 한계 CPA로 판단합니다 — 평균은 과거 성적표고 한계는 다음 1원의 가격표입니다. 포화지수(한계 CPA ÷ 평균 CPA)가 1보다 크게 높으면 증액분이 그만큼 안 나오고, 지출이 거의 일정했던 채널은 곡선을 못 그려 판정 자체가 보류됩니다.",
  "campaign-anomaly-detection": "캠페인 이상탐지는 'CPA가 20% 올랐다'가 아니라 '평소 변동폭을 넘어섰다'에만 반응하도록 기준을 잡아야 알림이 쓸모 있어집니다. 이상이 잡히면 숫자가 변한 사실보다 무엇이 변했는지를 기간·전환량·비용·믹스로 분해해야 원인이 나옵니다.",
  "cannibalization-organic-paid": "카니발라이제이션은 유료 광고가 어차피 왔을 오가닉 유입을 대신 가져가는 현상입니다. 브랜드 캠페인을 껐을 때 유료 전환 100건이 사라지고 오가닉이 70건 늘었다면 잠식률은 70%이고 순증분은 30건이므로, 리포트의 CPA를 3배로 다시 계산해 판단해야 합니다.",
  "cohort-analysis-guide": "D7 리텐션은 코호트 시작일로부터 최소 7일이 지난 유저만 넣어 계산해야 합니다. 데이터 최대 날짜가 7월 30일이면 D7은 7월 23일 코호트까지, D30은 6월 30일 코호트까지만 볼 수 있고, 덜 익은 코호트를 0으로 섞으면 최근 코호트가 급락한 것처럼 보입니다.",
  "content-element-analysis": "콘텐츠 요소 분석은 후킹·길이·형식을 0/1이나 숫자 열로 만들어 한 번에 비교하는 방법입니다. 요소들이 늘 같이 움직였다면 하나씩 봐서는 구분되지 않고, 종속변수가 CTR 같은 비율인지 조회수 같은 건수인지에 따라 맞는 모형도 달라집니다.",
  "correlation-vs-causation": "상관관계는 두 지표가 함께 움직였다는 관찰이고, 인과관계는 한쪽이 다른 쪽을 만들었다는 주장입니다. 둘을 가르는 가장 흔한 함정은 시즌·프로모션·가격 변동처럼 둘 다를 움직인 제3의 원인이므로, 대조군이나 무작위 실험처럼 다른 설명을 줄이는 설계가 있어야 인과를 말할 수 있습니다.",
  "cpi-cpa-cpm-difference": "CPM은 노출 1,000회당 비용이고 CPC는 클릭당 비용이며, 둘은 CPC = CPM ÷ CTR로 이어집니다. 그래서 CPC가 200원에서 300원이 됐을 때 CPM이 올랐으면 경매가 비싸진 것이고 CTR이 1%에서 0.67%로 떨어진 것이면 소재 문제라, 같은 증상에 처방이 정반대입니다.",
  "creative-attribute-regression": "썸네일·제목을 A/B 없이 비교하려면 이미 집행한 소재의 속성을 0/1 또는 숫자 열로 만들어 한꺼번에 회귀로 봅니다. '임팩트 있는 후킹' 같은 주관 열은 성과 좋은 소재에만 1이 찍혀 결과를 오염시키므로 사실만 열로 넣고, 신뢰구간이 0을 걸치는 속성은 쓰지 마세요.",
  "event-taxonomy-guide": "이벤트 택소노미는 행동을 이벤트 이름으로, 맥락을 파라미터로 분리해야 GA4·MMP·광고 매체·내부 리포트가 같은 행동을 같은 뜻으로 읽습니다. 새로 이름을 만들기 전에 GA4 권장 이벤트를 먼저 확인하고, 제품 정의와 맞을 때는 그대로 쓰세요.",
  "funnel-dropoff-analysis": "퍼널 이탈은 단계별 통과율을 세워 가장 낮은 칸부터 봅니다 — 클릭의 40%가 설치까지 와도 그중 25%만 가입하면 나머지 75%가 앱을 깔고 그냥 나가는 것입니다. 다만 통과율이 가장 낮은 칸이 아니라 개선 여지 × 트래픽 규모가 가장 큰 칸이 우선순위입니다.",
  "ga4-data-traps": "GA4 숫자가 다른 건 대부분 고장이 아니라 집계 기준 차이입니다 — 세션 정의, 처리 지연, 카디널리티 임계값, 귀속 모델이 다른 도구와 다르기 때문입니다. 설정을 고치기 전에 비교할 범위와 기준을 먼저 맞추면, 귀속 차이를 버그로 오해해 불필요한 세팅을 건드리는 일을 막을 수 있습니다.",
  "google-uac-optimization": "Google UAC에서 통제 가능한 건 입찰 목표·에셋 다양성·전환 이벤트 셋뿐이고, 타겟과 게재 위치는 시스템이 정합니다. 최근 30일 안에 예산·목표 단가·에셋 변경을 주 2회 넘게 했다면 캠페인이 계속 학습 상태에 머물러 있을 가능성이 크니, 설정보다 변경 빈도를 먼저 의심하세요.",
  "hook-3-seconds-framework": "영상 광고의 이탈은 첫 3초 안에 일어나므로, 그 안에 '이게 나랑 무슨 상관인지'를 납득시키지 못하면 뒤 내용은 아무도 보지 않습니다. 다만 모든 소재에 같은 후킹 공식이 통하지는 않으니, 타깃의 문제·메시지·형식을 바꾼 소재를 실제 이탈률로 비교해 검증하세요.",
  "incrementality-measurement": "증분성은 리포트에 찍힌 전환이 아니라 광고가 없었다면 사라졌을 전환입니다 — 마케팅 전환 500건 중 실제 증분은 120건이고 나머지 380건은 원래 올 손님이었을 수 있습니다. ROAS 800%가 찍혀도 증분이 낮으면 증액 근거가 되지 않으므로, 무작위 홀드아웃으로 확인하는 것이 가장 확실합니다.",
  "ios-att-skan-guide": "iOS 성과가 반토막으로 보이면 캠페인보다 측정을 먼저 의심하세요 — ATT 거부는 광고 노출이 아니라 유저 단위 측정을 막습니다. SKAN 4는 0~2일·3~7일·8~35일 세 창에서 포스트백을 주지만 정밀한 fine 값(0~63)은 첫 창에서 개인정보 임계를 넘을 때만 오고, 나머지는 low·medium·high 세 단계뿐입니다.",
  "ltv-cac-ratio": "LTV:CAC는 3:1이 흔한 기준선이지만, 그 비율을 보기 전에 계산이 맞는지부터 확인해야 합니다. 결제 고객 획득에 5,000만 원을 써서 500명을 데려왔다면 CAC는 10만 원이고, 이들이 월 2만 원씩 평균 12개월 남으면 LTV는 24만 원이라 2.4:1인데, 분모에 무엇을 넣었는지(광고비만인지 인건비 포함인지)에 따라 이 값이 통째로 달라집니다.",
  "marketing-mix-modeling": "MMM(마케팅 믹스 모델링)은 주별 채널 지출과 매출을 놓고 '매출 = 베이스라인 + 채널별 기여 + 외부요인'을 추정하는 방법입니다. 결과는 '다음 달 1억' 같은 점 예측이 아니라 95% 구간으로 읽어야 하고, 관측 데이터 기반이라 연관이지 인과가 아닙니다.",
  "multicollinearity-mmm-guide": "MMM에서 특정 채널 기여도가 음수로 나오면 모델 고장보다 다중공선성을 먼저 의심하세요. 검색과 소셜 예산을 늘 같이 올리고 내렸다면 모델은 둘 중 누가 결과를 만들었는지 구분할 근거가 없고, 이때 VIF가 높게 나오는 것은 '효과가 없다'가 아니라 '이 데이터로는 분리할 수 없다'는 뜻입니다.",
  "meta-advantage-plus-guide": "iOS 14.5 이후 Meta는 앱당 최대 8개 이벤트만 최적화 신호로 쓸 수 있고(Aggregated Event Measurement), 이 8개의 우선순위가 알고리즘이 무엇을 최적화할지를 정합니다. 기본 어트리뷰션이 7일 클릭 + 1일 조회라 다른 도구와 숫자가 다른 것도 정상이니, 비교 전에 창부터 맞추세요.",
  "offline-ad-online-impact": "TV·옥외 광고 효과는 클릭이 없으므로 브랜드 검색량·직접 유입 같은 온라인 흔적을 두 척도로 봅니다 — 집행 전 8주 이상 추세를 기준선으로 둔 주 단위 비교와, 방영 직후 15~60분 트래픽이 평소 같은 요일·시간대를 벗어났는지 보는 시간 단위 확인입니다. 같은 기간 디지털 예산을 함께 올리면 분리가 불가능하니 '집행 3주간 디지털 고정'을 미리 합의해두세요.",
  "performance-marketer-skills": "퍼포먼스 마케터에게 필요한 건 툴 암기가 아니라 문제 정의·데이터 품질 확인·실험 설계·결과 해석 순서입니다. 실무에서는 스프레드시트를 제대로 쓰는 것이 8할이고, 매체 광고 관리자는 하나만 손에 익혀도 충분합니다.",
  "performance-marketing-analysis-order": "퍼포먼스 마케팅 분석은 분석 이름부터 고르지 말고, 지금 답해야 할 질문과 가진 데이터의 단위부터 확인하세요. 일별 성과는 대시보드와 변동 분해, 지출 변화가 충분하면 포화도와 예산 배분, 대조군이 있으면 증분 분석, 52주 이상 채널 패널이 있으면 VIF를 거쳐 MMM으로 이어가는 순서가 안전합니다.",
  "performance-marketing-metrics": "퍼포먼스 마케팅 지표는 개별로 보지 말고 광고비 → CPI → CPA → ROAS → LTV:CAC 사슬로 세워 어느 칸이 빨간불인지부터 찾으세요. 광고비 500만원에 설치 5,000건이면 CPI 1,000원, 매출 1,500만원이면 ROAS 300%처럼 각 칸이 다른 질문에 답하므로, CPA는 좋은데 ROAS가 낮으면 문제는 광고 앞단이 아니라 전환 후 객단가입니다.",
  "postback-integration-guide": "포스트백 문제는 '설치가 0이다'만 보면 오래 걸리므로, 매체가 설치를 받는 방식이 SAN인지 S2S인지부터 확인하세요. 연동 방식에 따라 점검할 지점이 완전히 달라지고, S2S면 MMP와 매체 사이 서버 전송 규칙과 인증부터 봐야 합니다.",
  "retargeting-reengagement-guide": "리타겟팅은 이미 우리를 아는 사람이 대상이라 CPA가 낮게 나오므로 신규 획득(UA)과 반드시 분리해야 합니다. 신규 CPA 30,000원과 리타겟팅 CPA 6,000원을 합쳐 18,000원으로 보면 어느 캠페인의 현실도 아닌 숫자가 나오고, 실제 증분은 오디언스의 5~10%를 홀드아웃으로 빼봐야 알 수 있습니다.",
  "roas-improvement": "ROAS가 떨어졌을 때 예산부터 줄이면 원인을 못 찾습니다 — 전체 ROAS가 300%여도 채널마다 편차가 크기 때문입니다. 데이터 성숙도와 채널별 효율, 전환 이후 객단가를 먼저 나눠 보고, 재배분은 '좋아 보이는 곳에 몰기'가 아니라 다음 1원이 어디서 더 나은 결과를 만들지로 판단하세요.",
  "uplift-holdout-guide": "업리프트는 광고를 본 그룹과 홀드아웃 그룹의 전환율 차이입니다 — 노출군 8%, 홀드아웃 5%면 업리프트는 3%p입니다. 무작위 배정이 아니거나 두 그룹의 기간·대상이 다르면 이 차이를 광고 효과로 볼 수 없고, 구간이 0을 걸치면 '효과 없음'이 아니라 '아직 구분 안 됨'으로 읽어야 합니다.",
  "skan4-migration-guide": "SKAN 4 전환은 첫 창(0~2일) 컨버전 밸류 스키마부터 확정하고, 그다음 캠페인 구조를 iOS 기준으로 합친 뒤, 창 2·3은 필요해질 때 붙이는 순서가 안전합니다. 창 2·3은 low·medium·high 세 단계뿐이라 나중에 붙여도 손실이 적지만, 첫 창 매핑을 바꾸면 그 전후 데이터 비교가 끊깁니다.",
  "skan-conversion-value-schema": "SKAN 컨버전 밸류는 6비트 64칸이고, 담고 싶은 걸 다 넣으면 칸당 볼륨이 무너집니다. 하루 설치 500건을 64칸으로 쪼개면 칸당 평균 8건이라 노이즈가 신호를 덮으므로, '이 값이 달라지면 다른 행동을 하는가'를 기준으로 판단이 갈리는 지점만 나누세요.",
  "skan-vs-mmp-attribution": "SKAN 어트리뷰션과 MMP 숫자는 원래 안 맞습니다 — 집계 단위(캠페인 vs 유저), 도착 시점(무작위 지연 vs 실시간), ATT 거부 유저 포함 여부가 다르기 때문입니다. 합치려 하지 말고 유저 단위 분석은 MMP, iOS 캠페인 간 비교는 SKAN, 실제 기여는 증분 분석으로 나누세요.",
};

const EN_ANSWERS = {
  "ab-testing": "A/B testing is not eye-balling 4.2% against 4.8% — it is judging whether that gap sits outside the range of chance. Fix the sample size and stop date before launch, because stopping on day 3 turns a difference that later settles at +0.4pp into a false landslide.",
  "ad-creative-specs-guide": "Creatives get rejected or cropped because aspect ratios (1:1, 9:16), minimum resolutions, and file-size caps differ by platform. Do not ship one universal file — check each platform's spec and an actual preview before launch.",
  "ad-creative-testing": "You cannot fix the number of creatives at 'three at a time'; divide the test batch budget by the per-creative decision budget and round down. That result is how many operational slots you have, not a statistical sample size, and the goal is not to crown this week's CTR winner.",
  "ad-machine-learning": "The ad learning phase ends at roughly 50 optimization events within 7 days on Meta. Changing budget, targeting, or creative inside that window restarts learning, so make one change at a time and delay judgement until delivery stabilises.",
  "ad-performance-diagnosis": "When ad performance drops, do not swap creative first — narrow in this order: measurement setup, conversion volume, traffic quality, then creative. Comparing conversion counts across the ads manager, GA4, your MMP, and the payment database separates a tracking problem from a real performance problem in one step.",
  "adjust-vs-appsflyer": "Neither Adjust nor AppsFlyer is absolutely better for every team. Compare them against your actual requirements — measurement scope, network integrations, data access such as log-level export, and support — and confirm specifications with each vendor before signing.",
  "aha-event-ad-optimization": "Two users both register as one install, but one leaves after 10 seconds and the other uses a core feature and returns days later. When install CPA is low while Aha-event reach and D7 retention are also low, you did not buy users cheaply — you bought churn cheaply.",
  "aha-moment-retention": "An Aha moment is a candidate early action defined with both timing and count — 'added 3 friends within 3 days of signup' — not a single truth. Appearing alongside high retention does not make it causal (motivated users add more friends anyway), so drive it in onboarding and check whether retention actually moves.",
  "ai-era-marketer": "AI can produce 100 creatives, and all 100 are wasted if the direction is wrong. Defining the objective, validating the data, reading causation, and designing experiments — deciding what to make and whether to believe the result — still belong to the marketer.",
  "apple-search-ads-guide": "In Apple Search Ads (ASA), promote non-Exact search terms only after they have enough taps and installs and meet target CPA. Raise CPT slightly when pacing is low and performance is good; lower it when spend is high and performance misses target.",
  "asa-keyword-expansion": "ASA keyword expansion means using Discovery to find search terms, then promoting to Exact only those with enough conversions to judge on and a CPA inside target. A term showing $4 CPA on two conversions routinely settles at $30 once volume runs through it, so require both conditions — and add every promoted term as a Discovery negative so you stop bidding against yourself.",
  "aso-basics-guide": "ASO is a multiplier that sits in front of ad spend: at 10,000 product page views, moving conversion from 30% to 40% takes installs from 3,000 to 4,000 — 33% more installs and 25% lower CPI on the same budget. If views are high but installs are not, fix screenshots, icon, and rating; if views themselves are low, fix keywords and title.",
  "attribution-data-mismatch": "Attribution mismatch is normal — the same week can read 120 conversions in Meta, 70 in GA4, 85 in your MMP, and 100 in the payment database. None of them is broken; attribution windows, timing, and conversion definitions differ, so align those rules in one table before picking a number.",
  "audience-broad-vs-narrow": "Broad versus narrow targeting is decided by whether the account has enough conversion signal for the algorithm to learn on. Narrowing a low-conversion account starves learning, while opening wide on a product that genuinely fits one segment just raises CPA.",
  "brand-campaign-lift": "A brand campaign is judged on a time series, not on clicks, because someone who sees the ad and later searches your brand name converts under brand search or direct traffic. Use at least 8 pre-flight weeks as the baseline and read the gap above that trend with an interval that accounts for week-to-week autocorrelation.",
  "budget-marginal-efficiency": "Marketing budget allocation decisions belong to the marginal efficiency of the next unit of spend, not to average ROAS or CPA. There is no universal 20–30% step rule; start with channels whose next-dollar ROAS still sits above your target line.",
  "budget-scaling-limit": "Scale on marginal CPA, not average CPA — the average is a report card on the past and the margin is the price tag on the next unit of spend. A saturation index (marginal ÷ average CPA) well above 1 means added budget returns proportionally less, and a channel whose spend barely varied cannot produce a curve at all, so its verdict is withheld.",
  "campaign-anomaly-detection": "Anomaly alerts are only useful when they fire on 'outside normal variation' rather than on 'CPA rose 20%'. Once one fires, decompose what changed — period, conversion volume, cost, mix — because the fact that a number moved is not yet a cause.",
  "cannibalization-organic-paid": "Cannibalization is paid advertising taking traffic that would have arrived organically. If pausing a brand campaign removes 100 paid conversions while organic rises by 70, the cannibalization rate is 70% and real lift is 30, so that campaign's reported CPA needs to be recalculated at roughly three times what the dashboard shows.",
  "cohort-analysis-guide": "D7 retention must be calculated only from users at least 7 days past their cohort start date. If your data ends July 30, D7 is readable through the July 23 cohort and D30 through the June 30 cohort — mixing immature cohorts in as zeros makes recent cohorts look like a collapse that never happened.",
  "content-element-analysis": "Content element analysis turns hook, length, and format into 0/1 or numeric columns and compares them in one pass. Elements that always travelled together cannot be separated one at a time, and the right model differs depending on whether the outcome is a rate like CTR or a count like views.",
  "correlation-vs-causation": "Correlation is the observation that two metrics moved together; causation is the claim that one produced the other. The usual culprit between them is a third cause — season, promotion, price change — moving both, so you need a design such as a control group or randomization before claiming cause.",
  "cpi-cpa-cpm-difference": "CPM is cost per 1,000 impressions and CPC is cost per click, connected as CPC = CPM ÷ CTR. So when CPC moves from $0.20 to $0.30, a rising CPM means the auction got expensive while CTR falling from 1% to 0.67% means the creative stopped working — identical symptom, opposite fixes.",
  "creative-attribute-regression": "To compare thumbnails and titles without an A/B test, turn the attributes of creatives you already served into 0/1 or numeric columns and regress them together. Subjective columns like 'strong hook' end up flagged only on winners and poison the result, so record facts only and discard any attribute whose interval crosses zero.",
  "event-taxonomy-guide": "An event taxonomy works when the action is the event name and the context lives in parameters, so GA4, your MMP, ad platforms, and internal reports read the same behavior the same way. Check GA4's recommended events before inventing a name, and use them directly when they fit your product definition.",
  "funnel-dropoff-analysis": "Read funnel drop-off by laying out pass-through rates and starting at the weakest step — if 40% of clicks install but only 25% of those sign up, three quarters of installers leave without an account. Prioritise by room for improvement × traffic volume, though, not simply by the lowest rate.",
  "ga4-data-traps": "GA4 numbers usually differ because of counting rules, not bugs — session definition, processing latency, cardinality thresholds, and attribution model all differ from other tools. Align the comparison scope and definitions before changing settings, or you will 'fix' an attribution difference that was never broken.",
  "google-uac-optimization": "In Google UAC you control three levers — bid goal, asset diversity, and conversion events — while targeting and placements are decided by the system. If budget, target CPA, or assets changed more than twice a week over the last 30 days, suspect change frequency before settings: the campaign is likely living permanently in learning.",
  "hook-3-seconds-framework": "Video ad drop-off happens inside the first 3 seconds, so if the viewer cannot see what it has to do with them in that window, nothing after it gets watched. No single hook formula fits every creative, though — compare variants that change the audience problem, message, and format against actual drop-off data.",
  "incrementality-measurement": "Incrementality is not the conversions in your report but the ones that would disappear without the ad — of 500 marketing conversions, only 120 may be incremental while 380 were coming anyway. A reported ROAS of 800% is not a scaling case if lift is low, and a randomized holdout is the only design that settles it.",
  "ios-att-skan-guide": "If iOS looks cut in half, suspect measurement before the campaign — declining ATT blocks user-level measurement, not delivery. SKAN 4 returns postbacks in three windows (days 0–2, 3–7, 8–35), but the fine value (0–63) arrives only in the first window and only above the privacy threshold; everything else is low, medium, or high.",
  "ltv-cac-ratio": "LTV:CAC of 3:1 is a common reference line, but check the arithmetic before trusting the ratio. Spending $50,000 to acquire 500 paying customers gives CAC of $100, and if they spend $20 a month for 12 months LTV is $240 — a 2.4:1 ratio that shifts entirely depending on whether the denominator holds media spend alone or headcount too.",
  "marketing-mix-modeling": "Marketing mix modeling (MMM) takes weekly channel spend and revenue and estimates revenue = baseline + per-channel contribution + external factors. Read the output as a 95% interval rather than a point forecast like 'next month is $1M', and treat it as association from observational data, not causation.",
  "multicollinearity-mmm-guide": "When an MMM channel comes back with a negative coefficient, suspect multicollinearity before assuming the model broke. If search and social budgets always rose and fell together, the model has no basis to separate them, and a high VIF means 'this data cannot separate these channels' — not 'this channel does not work'.",
  "meta-advantage-plus-guide": "Since iOS 14.5, Meta allows at most 8 events per app as optimization signal (Aggregated Event Measurement), and how you rank those 8 decides what the algorithm optimizes for. Its default attribution is 7-day click plus 1-day view, so numbers differing from other tools is expected — align the windows before comparing.",
  "offline-ad-online-impact": "TV and out-of-home have no clicks, so read their online traces on two scales: a weekly comparison against a baseline of at least 8 pre-flight weeks, and an hourly check on whether traffic 15–60 minutes after a spot departs from the usual level for that weekday and hour. Raising digital budget in the same window makes separation impossible, so agree to hold digital flat for the flight beforehand.",
  "performance-marketer-skills": "What a performance marketer needs is not tool memorisation but an order: problem definition, data quality checks, experiment design, then interpretation. In practice spreadsheet fluency carries most of the work, and one ads manager learned properly is enough.",
  "performance-marketing-analysis-order": "Performance marketing analysis starts with the decision and the grain of the data, not the name of a method. Use daily performance for monitoring and variance decomposition, spend variation for saturation and allocation, a control for incrementality, and a 52+ week channel panel with a VIF check before MMM.",
  "performance-marketing-metrics": "Read performance marketing metrics as one chain — spend → CPI → CPA → ROAS → LTV:CAC — and find which cell is red before acting. $50,000 producing 5,000 installs is a $10 CPI, and $150,000 revenue on that spend is 300% ROAS; when CPA is good but ROAS is not, the problem sits after the conversion in order value, not in the ad.",
  "postback-integration-guide": "Debugging postbacks by staring at 'installs are zero' takes far too long — start by confirming whether the network receives installs via SAN or S2S. The integration type changes which checkpoints matter, and for S2S the server-to-server transfer rules and authentication between your MMP and the network come first.",
  "retargeting-reengagement-guide": "Retargeting reaches people who already know you, so its CPA reads low and it must be separated from new-user acquisition. Blending $30 acquisition CPA with $6 retargeting CPA produces $18 — a number describing neither campaign — and the real lift only becomes visible when you hold out 5–10% of the audience.",
  "roas-improvement": "Cutting budget first when ROAS falls hides the cause, because blended 300% ROAS can sit on top of very different per-channel results. Separate data maturity, per-channel efficiency, and post-conversion order value first, and reallocate by asking where the next dollar performs better rather than piling into whatever looks best.",
  "uplift-holdout-guide": "Uplift is the conversion-rate gap between an exposed group and a holdout — 8% exposed against 5% held out is 3pp of uplift. Without random assignment, or when the two groups differ in period or audience, that gap is not ad effect, and an interval crossing zero means 'not yet distinguishable', not 'no effect'.",
  "skan4-migration-guide": "SKAN 4 migration is safest in this order: lock the first window (days 0–2) conversion-value schema, consolidate campaign structure for iOS, then add windows 2 and 3 when you need them. The later windows return only low, medium, or high, so adding them late costs little — but remapping the first window breaks comparison across the change.",
  "skan-conversion-value-schema": "The SKAN conversion value is six bits — 64 slots — and encoding everything collapses volume per slot. Splitting 500 daily installs across 64 slots averages eight each, where noise buries signal, so split only where the value changes what you would actually do.",
  "skan-vs-mmp-attribution": "SKAN attribution and MMP numbers are supposed to disagree: they differ in unit (campaign versus user), arrival (randomised delay versus real time), and whether ATT-declined users are included. Rather than reconciling them, use the MMP for user-level analysis, SKAN for comparing iOS campaigns, and incrementality for actual contribution.",
};

const CONDITION_GROUP_BY_SLUG = {
  "ab-testing": "experiment", "aha-event-ad-optimization": "causal", "aha-moment-retention": "causal",
  "cannibalization-organic-paid": "causal", "correlation-vs-causation": "causal", "incrementality-measurement": "causal",
  "marketing-mix-modeling": "causal", "ad-creative-specs-guide": "platform", "ad-creative-testing": "creative", "ad-machine-learning": "platform",
  "multicollinearity-mmm-guide": "causal",
  "brand-campaign-lift": "causal", "offline-ad-online-impact": "causal", "budget-scaling-limit": "economics",
  "content-element-analysis": "creative", "creative-attribute-regression": "creative", "asa-keyword-expansion": "platform",
  "adjust-vs-appsflyer": "platform", "apple-search-ads-guide": "platform", "aso-basics-guide": "platform",
  "google-uac-optimization": "platform", "ios-att-skan-guide": "platform", "meta-advantage-plus-guide": "platform",
  "postback-integration-guide": "platform", "ad-performance-diagnosis": "measurement", "attribution-data-mismatch": "measurement",
  "campaign-anomaly-detection": "measurement", "cohort-analysis-guide": "measurement", "cpi-cpa-cpm-difference": "measurement",
  "event-taxonomy-guide": "measurement", "funnel-dropoff-analysis": "measurement", "ga4-data-traps": "measurement",
  "performance-marketing-metrics": "measurement", "budget-marginal-efficiency": "economics", "ltv-cac-ratio": "economics",
  "performance-marketing-analysis-order": "measurement",
  "audience-broad-vs-narrow": "creative", "hook-3-seconds-framework": "creative", "retargeting-reengagement-guide": "creative",
  "ai-era-marketer": "editorial", "performance-marketer-skills": "editorial",
  "roas-improvement": "economics",
  "uplift-holdout-guide": "causal",
  "skan4-migration-guide": "measurement", "skan-conversion-value-schema": "measurement", "skan-vs-mmp-attribution": "measurement",
};

const CONDITIONS = {
  ko: {
    experiment: "무작위 배정, 사전 종료 기준, 서로 독립인 관측치가 확보된 실험에 적용합니다. 표본이 작거나 중간 결과를 반복 확인했다면 판정을 보수적으로 해석하세요.",
    causal: "관측 데이터의 연관성만으로 인과를 확정할 수 없습니다. 대조군의 비교 가능성, 동시 변화, 표본 규모를 확인하고 중요한 결정은 실험으로 검증하세요.",
    platform: "매체 정책과 제품 기능은 바뀔 수 있습니다. 계정 유형·국가·측정 설정을 확인하고 집행 시점의 공식 문서를 최종 기준으로 사용하세요.",
    measurement: "같은 기간, 시간대, 전환 정의, 집계 단위를 맞춘 비교에 적용합니다. 모수와 누락 데이터를 확인하지 않은 비율 비교는 결론에서 제외하세요.",
    economics: "비용·매출·고객 범위와 관찰 기간을 동일하게 맞춘 데이터에 적용합니다. 미래 효율은 추정치이므로 작은 예산 단계로 검증하세요.",
    creative: "타깃, 지면, 메시지, 노출 빈도가 비슷한 조건의 비교에 적용합니다. 매체 평균보다 실제 계정의 전환량과 소재 실험 결과를 우선하세요.",
    editorial: "팀의 역할과 제품 단계에 따라 우선순위가 달라지는 편집 관점입니다. 채용 요건이나 조직 설계를 위한 보편적 기준으로 단정하지 마세요.",
  },
  en: {
    experiment: "This applies to experiments with random assignment, a pre-set stopping rule, and independent observations. Treat the result conservatively if the sample is small or repeatedly inspected mid-test.",
    causal: "Observational association alone does not establish causality. Check control-group comparability, simultaneous changes, and sample size, then validate consequential decisions with an experiment.",
    platform: "Platform policies and product behavior can change. Check account type, country, and measurement setup, and use the current official documentation as the final operating reference.",
    measurement: "This applies when date range, time zone, conversion definition, and aggregation grain are aligned. Exclude ratio comparisons whose denominator or missingness has not been checked.",
    economics: "Align cost, revenue, customer scope, and observation window. Future efficiency is an estimate, so validate it through small budget steps.",
    creative: "Compare like-for-like audiences, placements, messages, and frequency. Prefer conversion volume and creative-test evidence from the actual account over platform-wide averages.",
    editorial: "This is an editorial perspective whose priorities depend on team role and product stage. Do not treat it as a universal hiring or organization-design standard.",
  },
};

export function getBlogEditorial(locale, slug, source = {}) {
  const lang = locale === "en" ? "en" : "ko";
  const answer = source.answer || (lang === "en" ? EN_ANSWERS[slug] : KO_ANSWERS[slug]) || "";
  const conditionGroup = CONDITION_GROUP_BY_SLUG[slug] || "measurement";
  const conditions = source.conditions || CONDITIONS[lang][conditionGroup];
  return {
    answer,
    conditions,
    // 실제 검토 정보가 원고에 있을 때만 노출한다. 발행일을 검토일로 바꾸지 않는다.
    reviewer: source.reviewer || "",
    reviewedAt: source.reviewedAt || "",
    sources: Array.isArray(source.sources) ? source.sources.filter((item) => item?.title && item?.url) : [],
  };
}

export function publishedEditorialSlugs(locale) {
  return Object.keys(locale === "en" ? EN_ANSWERS : KO_ANSWERS)
    .filter((slug) => slug !== "adjust-vs-appsflyer");
}
