"""Rebuild self-hosted Unicode subsets. Requires fonttools[woff]==4.60.2.
Common Korean (KS X 1001), Latin and UI punctuation load together; remaining
characters retain full coverage via disjoint unicode-range chunks.
Original fonts and their licenses remain in public/fonts for reproducibility.
"""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
import hashlib

root = Path(__file__).resolve().parents[1]
out = root / 'public/fonts/subsets'
out.mkdir(exist_ok=True)
common = set(range(0x250)) | set(range(0x2000, 0x2070)) | set(range(0x20A0, 0x20D0))
for code in range(0xAC00, 0xD7A4):
    try:
        if len(chr(code).encode('euc_kr')) == 2: common.add(code)
    except UnicodeEncodeError: pass

def ranges(points):
    result = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1: end = point
        else:
            result.append(f'U+{start:X}-{end:X}' if start != end else f'U+{start:X}')
            start = end = point
    result.append(f'U+{start:X}-{end:X}' if start != end else f'U+{start:X}')
    return ','.join(result)

generated = set()
css = ['/* Generated by scripts/subset-korean-fonts.py; do not hand edit. */']
for family, source, weight in [('GOP Heading', 'PretendardVariable', '100 900'), ('Wanted Sans Subset', 'WantedSansVariable', '400 1000')]:
    path = root / f'public/fonts/{source}.woff2'
    points = set(TTFont(path).getBestCmap())
    rare = sorted(points - common)
    groups = [sorted(points & common)] + [rare[i:i+512] for i in range(0, len(rare), 512)]
    covered = set()
    for i, chars in enumerate(groups):
        font = TTFont(path, recalcTimestamp=False)
        options = subset.Options()
        options.flavor = 'woff2'
        worker = subset.Subsetter(options=options)
        worker.populate(unicodes=chars)
        worker.subset(font)
        assert not covered.intersection(chars)
        covered.update(chars)
        assert set(chars) <= set(font.getBestCmap())
        temp = out / f'{source}-{i}.woff2'
        # Pretendard reserves its font name under OFL. Rename modified fonts,
        # retaining copyright and license records intact.
        if source == 'PretendardVariable':
            for record in font['name'].names:
                if record.nameID in (1, 3, 4, 6, 16, 21) or record.nameID >= 256:
                    value = record.toUnicode().replace('Pretendard', 'GOPHeading')
                    record.string = value.encode(record.getEncoding())
        font.save(temp)
        digest = hashlib.sha256(temp.read_bytes()).hexdigest()[:12]
        target = out / f'{source}-{i}-{digest}.woff2'
        temp.rename(target)
        generated.add(target.name)
        css.append(f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};font-display:swap;src:url("/fonts/subsets/{target.name}") format("woff2");unicode-range:{ranges(chars)};}}')
        if i == 0: print(source, 'common bytes', target.stat().st_size)
    assert covered == points
    print(source, 'coverage', len(covered), 'chunks', len(groups))
css.append('@layer tokens { :root { --font-pretendard:"GOP Heading"; --font-wanted-sans:"Wanted Sans Subset"; } }')
(root / 'src/app/korean-fonts.css').write_text('\n'.join(css) + '\n')

for old in out.glob('*.woff2'):
    if old.name not in generated: old.unlink()
