import {test,expect} from '@playwright/test';
for(const locale of ['ko','en'])test(`board sync, portable copy and report evidence (${locale})`,async({page})=>{
 const en=locale==='en',t=(ko,eng)=>en?eng:ko;
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let boards=[];
 const entitlement={plan:'paid',account:true,payment:true,expiresAt:Date.now()+86400000,offlineUntil:Date.now()+3600000};
 await page.route('**/api/account/session',r=>r.fulfill({json:{enabled:true,account:{id:'board-test',email:'test@example.com'},entitlement}}));
 await page.route('**/api/payments/access',r=>r.fulfill({json:{entitlement}}));
 await page.route('**/api/account/recipes',r=>r.fulfill({json:{recipes:[],canApply:true}}));
 await page.route('**/api/account/boards',r=>{if(r.request().method()==='POST')boards=[{...r.request().postDataJSON().board,updatedAt:new Date().toISOString()}];return r.fulfill({json:{boards,canApply:true}})});
 await page.goto(`${en?'/en':''}/dashboard?example=1`);await expect(page.locator('#s-kpi')).toBeVisible();
 await page.getByRole('button',{name:t('대시보드 편집 · Pro','Edit dashboard · Pro'),exact:true}).click();
 const editor=page.locator('.dashboard-editor');
 await editor.getByRole('button',{name:t('차트 추가','Add chart'),exact:true}).click();
 await editor.getByLabel(t('차트 제목','Chart title')).fill('Private campaign title');
 await editor.getByRole('button',{name:t('배치','Layout'),exact:true}).click();
 await editor.getByLabel(t('구역 폭','Block width')).selectOption('half');
 await page.getByRole('button',{name:t('편집 저장','Save edits'),exact:true}).click();
 await page.getByRole('button',{name:t('보드 동기화·팀 공유','Board sync / team sharing'),exact:true}).click();
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();
 await dialog.getByLabel(t('구성 이름','Layout name'),{exact:true}).fill('Weekly');
 await dialog.getByRole('button',{name:t('계정에 저장','Save to account'),exact:true}).click();
 await expect(dialog.getByRole('status')).toContainText(t('계정에 저장했습니다.','Saved to your account.'));
 expect(boards).toHaveLength(1);expect(JSON.stringify(boards)).not.toMatch(/demo_efficiency|Meta|csvData|raw|dateStart|scope|Private campaign/);
 expect(boards[0].tabs.viz.charts).toHaveLength(1);
 expect(boards[0].tabs.viz.blocks['custom-0'].width).toBe('half');
 const downloadPromise=page.waitForEvent('download');await dialog.getByRole('button',{name:t('팀 공유 파일 받기','Download team layout')}).click();
 const download=await downloadPromise;expect(download.suggestedFilename()).toBe('dashboard-layout.gop.json');
 await dialog.locator('input[type="file"]').setInputFiles(await download.path());
 await expect(dialog.getByRole('status')).toContainText(t('편집 미리보기에 적용했습니다.','Applied to the editing preview.'));
 await dialog.getByRole('button',{name:t('미리보기 적용','Apply to preview')}).click();
 await dialog.getByRole('button',{name:t('닫기','Close'),exact:true}).click();
 await expect(page.locator('.dashboard-editor')).toBeVisible();
 await page.getByRole('button',{name:t('편집 저장','Save edits'),exact:true}).click();
 await expect(page.locator('.dashboard-layout-block[data-block-id="custom-0"]')).toHaveAttribute('data-width','half');
 await expect(page.locator('.dashboard-custom-block')).not.toContainText('Private campaign title');
 await page.getByRole('button',{name:t('현재 탭을 보고서에 담기 · Pro','Add this tab to report · Pro'),exact:true}).click();
 await expect(page.locator('.dashboard-workspace-notice')).toContainText(t('보고서에 담았습니다.','blocks from this tab to the report.'));
 await page.getByRole('link',{name:t('모은 보고서 보기','View collected report')}).click();
 await expect(page.locator('.report-block-evidence img').first()).toBeVisible();
 expect(await page.locator('.report-block-evidence img').count()).toBeGreaterThan(0);
 await expect(page.locator('main')).toContainText(t('예시 데이터','Sample data'));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
 expect(errors).toEqual([]);
});
