import { test, expect } from "@playwright/test";
import { enableReviewLogin, confirmReviewDialog } from "./support/reviewSave";
for (const locale of ["ko", "en"]) {
  test(`contribution hypothesis → organic holdout target → observed review (${locale})${locale === "en" ? " @light-en" : ""}`, async ({ page }) => {
    const en = locale === "en", prefix = en ? "/en" : "";
    await enableReviewLogin(page);
    await page.goto(`${prefix}/projects`);
    await expect(page.getByRole("button", { name: en ? "Create project" : "프로젝트 만들기", exact: true })).toBeEnabled();
    await page.evaluate(async () => {
      const db = await new Promise(resolve => { const request = indexedDB.open("mkt_workspace"); request.onsuccess = () => resolve(request.result); });
      const tx = db.transaction("meta", "readwrite");
      tx.objectStore("meta").put({ key: "project:default", id: "default", name: "Goal workflow", snapshots: [], settings: null, createdAt: Date.now(), lastUsedAt: Date.now(), decisions: [{ id: "attribution", toolId: "5-18", sourcePath: "/tools/marketing-response?stage=mmm", action: "Review contribution", actual: "Model reviewed", learning: "Validate Google brand", reviewDate: "2026-01-01", createdAt: "2025-12-25T00:00:00Z", status: "reviewed", goalMetric: "roas", goalDirection: "up", metric: "ROAS" }] });
      await new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = reject; }); db.close();
    });
    await page.goto(`${prefix}/weekly-review`);
    await page.getByText(en ? "Browse decisions by tool" : "도구별 결정 찾아보기", { exact: true }).click();
    await page.locator(".project-review-portfolio").getByRole("link", { name: en ? "Review these decisions" : "이 도구의 결정 검토" }).click();
    await page.getByRole("button", { name: en ? "Turn this learning into the next decision" : "배운 점으로 다음 결정 만들기" }).click();
    const form = page.locator(".decision-follow-up__form");
    await form.getByLabel(en ? "Next action" : "다음에 실행할 행동", { exact: true }).fill("Hold out Google brand");
    await form.getByLabel(en ? "Goal for the next decision" : "다음 결정의 목표").selectOption("rerun:organic_users");
    await form.getByText(en ? "Set a numeric target or experiment design" : "수치 목표·실험 설계 설정", { exact: true }).click();
    await form.getByRole("combobox", { name: en ? "Review method" : "검토 방법", exact: true }).selectOption("holdout");
    await form.getByLabel(en ? "Target channel / group" : "대상 채널·집단").fill("Google brand");
    await form.getByLabel(en ? "Comparison group" : "비교군", { exact: true }).fill("Control regions");
    await form.getByLabel(en ? "Observation window" : "관측 기간").fill("Oct 1–14");
    await form.getByLabel(en ? "Success threshold type" : "성공 기준 유형").selectOption("increase_percent");
    await form.getByLabel(en ? "Target value" : "목표값", { exact: true }).fill("10");
    await form.getByLabel(en ? "Measurement unit" : "측정 단위").fill("people");
    await form.getByLabel(en ? "Baseline for this decision" : "이번 결정의 기준값").fill("5000");
    await form.getByRole("button", { name: en ? "Save next decision" : "다음 결정 저장", exact: true }).click();
    await confirmReviewDialog(page, en);
    await page.reload();
    await expect(page.locator(".project-review-portfolio article")).toHaveCount(2);
    await page.evaluate(async () => {
      const db = await new Promise(resolve => { const request = indexedDB.open("mkt_workspace"); request.onsuccess = () => resolve(request.result); });
      const tx = db.transaction("meta", "readwrite"), store = tx.objectStore("meta");
      const req = store.get("project:default");
      req.onsuccess = () => { const project = req.result; const child = project.decisions.find(item => item.action === "Hold out Google brand"); project.decisions.push({ id: "effect-analysis", toolId: "5-23", dataOrigin: child.dataOrigin, action: "Read organic recovery experiment", createdAt: "2026-10-15T00:00:00Z", metric: "Organic users", evidence: JSON.stringify({ version: 1, headline: "Organic recovery estimate: +300 people", stats: [{ label: "95% CI", value: "+100 to +500 people" }], points: [{ text: "Check total conversions separately" }], scope: { start: "2026-10-01", end: "2026-10-14" } }) }); store.put(project); };
      await new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = reject; }); db.close();
    });
    await page.reload();
    await expect(page.locator(".project-review-portfolio article")).toHaveCount(3);
    await page.getByRole("button", { name: en ? "Review / export device records" : "기기 기록 검토·내보내기" }).click();
    const card = page.locator(".weekly-review-record").filter({ has: page.getByRole("heading", { name: "Hold out Google brand", exact: true }) });
    const actual = card.getByLabel(en ? "Target observation — Hold out Google brand" : "목표 관측값 — Hold out Google brand");
    await card.getByText(en ? "Saved operating target and design" : "저장한 운영 목표와 설계", { exact: true }).click();
    await expect(card).toContainText("Control regions");
    await actual.fill("5499");
    await expect(card.getByRole("status")).toContainText(en ? "Below target; this does not mean no effect" : "목표 미달 · 효과 없음이라는 뜻 아님");
    await actual.fill("5500");
    await expect(card.getByRole("status")).toContainText(en ? "Reached; effect evidence must be reviewed separately" : "목표 도달 · 효과 근거는 별도 검토");
    await actual.fill("5300");
    await expect(card.getByRole("status")).toContainText("+300 people (+6%)");
    await expect(card.getByRole("status")).toContainText("60%");
    await card.getByRole("checkbox", { name: en ? "Show other saved analyses (conditions may differ)" : "다른 저장 분석도 보기 (조건이 다를 수 있음)" }).check();
    await card.getByRole("combobox", { name: en ? "Link saved follow-up analysis" : "후속 분석 근거 연결" }).selectOption("effect-analysis");
    await card.getByRole("button", { name: en ? "Conditions checked — use this evidence" : "조건 확인 후 이 근거 사용" }).click();
    await expect(card).toContainText("+100 to +500 people");
    await card.getByRole("button", { name: en ? "Save review changes" : "검토 내용 저장", exact: true }).click();
    await confirmReviewDialog(page, en);
    await page.reload();
    await expect(page.locator(".project-review-portfolio article")).toHaveCount(3);
    await page.getByRole("button", { name: en ? "Review / export device records" : "기기 기록 검토·내보내기" }).click();
    await expect(actual).toHaveValue("5300");
    await expect(card).toContainText("+100 to +500 people");
    await page.keyboard.press("Escape");
    await page.locator(".project-review-portfolio").getByRole("button", { name: en ? "Share / download project review" : "프로젝트 리뷰 공유·다운로드" }).click();
    await page.getByRole("menuitem", { name: en ? /Preview my report/ : /내 보고서 미리보기/ }).click();
    const preview = page.getByRole("dialog", { name: en ? "Your report preview" : "내 보고서 미리보기" });
    await expect(preview).toContainText("Control regions"); await expect(preview).toContainText("10%"); await expect(preview).toContainText("5,300"); await expect(preview).toContainText("+100 to +500 people"); await expect(preview).toContainText("60%");
  });
}
