import { scoreMappingCandidates } from "@/lib/data-import/scoreMappingCandidates";

export const STANDARD_FIELDS = {
              date: {
                label: "날짜",
                labelEn: "Date",
                aliases: ["dt", "날짜", "일자", "event_date", "day"],
                type: "date",
                required: true,
                group: "디멘션",
              },
              snapshot_date: {
                label: "데이터 기준일(Snapshot)",
                aliases: ["snapshot_date", "snapshot", "as_of_date", "as_of", "export_date", "report_date", "download_date", "데이터기준일", "추출일", "다운로드일", "리포트일"],
                type: "date",
                required: false,
                group: "디멘션",
              },
              platform: {
                label: "플랫폼(OS)",
                aliases: ["os", "platform_name", "campaign_platform", "campaign_os", "mkt_platform", "플랫폼"],
                type: "enum",
                required: false,
                group: "디멘션",
              },
              channel: {
                label: "채널/매체",
                labelEn: "Channel",
                aliases: ["network", "source", "media", "매체", "채널"],
                type: "string",
                required: false,
                group: "디멘션",
                oneOfGroup: "grouping",
              },
              campaign_name: {
                label: "캠페인명",
                labelEn: "Campaign",
                aliases: ["campaign", "캠페인", "캠페인명"],
                type: "string",
                required: false,
                group: "디멘션",
                oneOfGroup: "grouping",
              },
              adgroup_name: {
                label: "광고그룹명",
                aliases: ["adgroup", "ad group", "ad_group", "adgroup name", "ad group name", "광고그룹", "광고 그룹", "광고그룹명"],
                type: "string",
                required: false,
                group: "디멘션",
              },
              search_term: {
                label: "검색어(ASA)",
                labelEn: "Search term (ASA)",
                aliases: ["search term", "search_term", "searchterm", "keyword text", "검색어", "검색어구문", "키워드"],
                type: "string",
                required: false,
                group: "ASA",
              },
              match_type: {
                label: "매치 타입(ASA)",
                aliases: ["match type", "match_type", "matchtype", "keyword match type", "매치타입", "매치 타입", "검색 일치 유형"],
                type: "string",
                required: false,
                group: "ASA",
              },
              daily_budget: {
                label: "일일 예산(ASA)",
                aliases: ["daily budget", "daily_budget", "dailybudget", "budget per day", "일일예산", "일일 예산"],
                type: "number",
                required: false,
                group: "ASA",
              },
              target_cpa: {
                label: "목표 CPA(ASA)",
                aliases: ["target cpa", "target_cpa", "goal cpa", "목표cpa", "목표 cpa"],
                type: "number",
                required: false,
                group: "ASA",
              },
              target_cpt: {
                label: "목표 CPT(ASA)",
                aliases: ["target cpt", "target_cpt", "goal cpt", "max cpt", "목표cpt", "목표 cpt"],
                type: "number",
                required: false,
                group: "ASA",
              },
              current_cpt: {
                label: "현재 CPT(ASA)",
                aliases: ["current cpt", "current_cpt", "avg cpt", "average cpt", "cpt bid", "bid amount", "bid", "현재cpt", "현재 cpt", "입찰가"],
                type: "number",
                required: false,
                group: "ASA",
              },
              country: {
                label: "국가",
                aliases: ["country", "mkt_country", "국가", "country_code", "마켓"],
                type: "string",
                required: false,
                group: "디멘션",
              },
              source: {
                // 광고 여부(오가닉 vs 페이드) 구분. 헤더명이 아니라 값(organic/paid…)으로
                // 판별한다 — valueVocabulary가 있으면 scoreMappingCandidates가 컬럼 값의
                // 상당수가 이 어휘에 들면 강하게 매핑한다. "source" 헤더 별칭은 channel이
                // 이미 갖고 있어(구글/메타 같은 매체) 여기엔 넣지 않는다 — 값 기반으로만.
                label: "소스(광고/오가닉)",
                aliases: ["media_source", "utm_source", "traffic_source", "매체구분", "유입구분", "광고구분", "소스구분", "organicpaid", "paidorganic"],
                type: "enum",
                required: false,
                group: "디멘션",
                valueVocabulary: [
                  "organic", "paid", "오가닉", "페이드", "owned", "earned",
                  "유료", "무료", "자연", "자연유입", "광고", "비광고",
                  "nonpaid", "non-paid", "unpaid", "paidmedia", "organictraffic",
                ],
              },
              cost: {
                label: "비용",
                labelEn: "Spend",
                aliases: ["spend", "total cost", "비용", "광고비", "소진액", "집행액", "amount spent", "media cost"],
                type: "number",
                required: true,
                group: "단일 지표",
              },
              impressions: {
                label: "노출수",
                labelEn: "Impressions",
                aliases: ["imp", "impression", "노출", "노출수"],
                type: "number",
                required: false,
                group: "단일 지표",
              },
              clicks: {
                label: "클릭수",
                labelEn: "Clicks",
                aliases: ["click", "taps", "tap", "클릭", "클릭수"],
                type: "number",
                required: false,
                group: "단일 지표",
              },
              event: {
                // 그날 우리가 한 행동(스크린샷 교체·가격 인하…). 차트에 세로선으로 찍혀
                // "이 조치가 어디에 영향을 줬나"를 눈으로 맞춰 보게 한다.
                label: "이벤트(액션 로그)",
                aliases: ["event", "action", "액션", "이벤트", "메모", "annotation", "note", "변경사항"],
                type: "string",
                required: false,
                group: "디멘션",
              },
              event_type: {
                label: "이벤트 종류",
                aliases: ["event_type", "action_type", "이벤트종류", "액션종류", "종류"],
                type: "string",
                required: false,
                group: "디멘션",
              },
              tenure_periods: {
                label: "생존 관측 기간",
                labelEn: "Survival observation duration",
                aliases: ["tenure", "tenure_periods", "survival_duration", "action survival duration", "time_to_event", "time to event", "duration_to_dropout", "subscription_tenure", "subscription tenure", "subscription duration", "observation duration", "tenure months", "months subscribed", "관측기간", "관측 기간", "구독기간", "구독 기간", "이용기간"],
                type: "number",
                required: false,
                group: "핵심 액션 생존",
              },
              event_observed: {
                label: "이탈·종료 이벤트 관측 (0/1)",
                labelEn: "Dropout or exit event observed (0/1)",
                aliases: ["event_observed", "event_occurred", "event occurred", "dropout_observed", "dropout observed", "exit_event", "exit observed", "churn_event", "churn observed", "observed churn", "churned", "is_churned", "cancelled", "이탈여부", "이탈 여부", "종료이벤트", "종료 이벤트", "해지여부", "해지 여부"],
                type: "number",
                required: false,
                group: "핵심 액션 생존",
              },
              subscription_start_date: {
                label: "관측 시작일",
                labelEn: "Observation start date",
                aliases: ["action_start_date", "action start date", "action_started_at", "cohort_start_date", "cohort start date", "subscription_start_date", "subscription start date", "subscription started at", "subscription_start", "start date", "started at", "핵심액션시작일", "핵심 액션 시작일", "관측시작일", "관측 시작일", "구독시작일", "구독 시작일", "가입일", "시작일"],
                type: "date",
                required: false,
                group: "핵심 액션 생존",
              },
              churn_date: {
                label: "이탈·종료 이벤트일",
                labelEn: "Dropout or exit event date",
                aliases: ["action_exit_date", "action exit date", "action_event_date", "action event date", "dropout_date", "dropout date", "inactivity_date", "churn_date", "churn date", "subscription churn date", "cancel date", "cancellation date", "cancelled at", "canceled at", "ended at", "이탈일", "종료일", "종료 이벤트일", "해지일", "해지 일자", "구독 종료일"],
                type: "date",
                required: false,
                group: "핵심 액션 생존",
              },
              observation_end_date: {
                label: "관측 종료일",
                labelEn: "Observation end date",
                aliases: ["action_observation_end_date", "action observation end date", "observation_end_date", "observation end date", "subscription end date", "observed until", "as of date", "snapshot date", "data extract date", "data extracted at", "관측종료일", "관측 종료일", "추출 기준일", "데이터 추출일", "기준일"],
                type: "date",
                required: false,
                group: "핵심 액션 생존",
              },
              entry_period: {
                label: "관측 진입 기간",
                labelEn: "Observation entry period",
                // 액션 생존 export는 "Observation Entry"처럼 기간의 기준점을 제목에
                // 풀어 쓰는 경우가 있다. 날짜형 entry가 아니라 0 이상 기간 수인
                // 생존 계약에만 매핑한다.
                aliases: ["entry_period", "observation_entry_period", "subscription_entry", "entry time", "entry period", "observation entry", "observation entry period", "observation start", "관측진입", "관측 진입", "관측 시작"],
                type: "number",
                required: false,
                group: "핵심 액션 생존",
              },
              plan: {
                label: "구독 플랜",
                labelEn: "Subscription plan",
                aliases: ["plan", "subscription_plan", "pricing_plan", "요금제", "구독플랜", "구독 플랜"],
                type: "string",
                required: false,
                group: "핵심 액션 생존",
              },
              promo: {
                label: "프로모션",
                labelEn: "Promotion",
                aliases: ["promo", "promotion", "promotion_type", "프로모션", "할인유형", "할인 유형"],
                type: "string",
                required: false,
                group: "핵심 액션 생존",
              },
              cac: {
                label: "개체 획득·유지비",
                labelEn: "Entity acquisition or maintenance cost",
                aliases: ["cac", "entity_cost", "entity acquisition cost", "customer_acquisition_cost", "acquisition cost", "maintenance cost", "획득비용", "유지비", "고객획득비용", "고객 획득비용"],
                type: "number",
                required: false,
                group: "핵심 액션 생존",
              },
              store_source: {
                // 스토어 유입 소스(App Store Search·Browse·Referrer / Play 검색·둘러보기).
                // `source`(광고/오가닉)와 다른 축이다 — 같은 키를 쓰면 매핑 화면 라벨이
                // 어긋나고, organic/paid 값 어휘로는 스토어 소스 값을 잡지 못한다.
                label: "유입 소스 (스토어)",
                labelEn: "Traffic source (store)",
                aliases: [
                  "source_type", "source type", "소스유형", "소스 유형",
                  "traffic_source", "traffic source", "트래픽소스", "트래픽 소스",
                  "유입소스", "유입 소스", "유입경로",
                ],
                type: "enum",
                required: false,
                group: "디멘션",
                // 값은 전부 3자 이상이라 짧은 토큰 오탐(§7)에서 자유롭다.
                valueVocabulary: [
                  "app store search", "app store browse", "app referrer", "web referrer",
                  "institutional purchase", "unavailable",
                  "google play search", "google play explore", "third-party referrers",
                  "앱스토어검색", "앱스토어둘러보기", "구글플레이검색", "구글플레이탐색",
                ],
              },
              product_page_views: {
                label: "제품 페이지 조회",
                labelEn: "Product page views",
                aliases: ["product_page_views", "product page views", "page_views", "store_listing_visitors", "listing_visitors", "제품페이지조회", "제품 페이지 조회", "스토어조회", "페이지조회"],
                type: "number",
                required: false,
                group: "지표",
              },
              installs: {
                label: "설치수",
                labelEn: "Installs",
                aliases: [
                  "install", "설치", "설치수", "inst",
                  // 스토어 콘솔 export 실제 컬럼명 — 없으면 5-27이 설치 열을 못 잡는다.
                  "total_downloads", "total downloads", "first_time_downloads", "first-time downloads",
                  "store_listing_acquisitions", "store listing acquisitions", "installers",
                  "다운로드", "총다운로드", "최초다운로드",
                ],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "outcome",
              },
              actions: {
                label: "액션/가입 수",
                labelEn: "Actions / signups",
                aliases: [
                  "action",
                  "actions",
                  "conversions",
                  "events",
                  "전환",
                  "액션",
                  "가입",
                  "가입수",
                  "가입 수",
                  "signup",
                  "signups",
                  "sign_up",
                  "sign_ups",
                  "registration",
                  "registrations",
                  "regs",
                  "reg",
                ],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "outcome",
              },
              brand_search: {
                label: "브랜드 검색량",
                labelEn: "Brand search volume",
                aliases: ["brand_search", "branded_search", "brand search", "브랜드검색", "브랜드 검색", "브랜드키워드", "branded queries"],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "brand_outcome",
              },
              direct_traffic: {
                label: "직접 유입",
                labelEn: "Direct traffic",
                aliases: ["direct_traffic", "direct traffic", "direct_sessions", "direct sessions", "직접유입", "직접 유입", "다이렉트유입"],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "brand_outcome",
              },
              campaign_on: {
                label: "브랜드 캠페인 집행 여부",
                aliases: ["campaign_on", "campaign active", "campaign_status", "brand_campaign_on", "브랜드캠페인", "브랜딩집행", "집행여부", "집행 여부", "캠페인온오프"],
                type: "enum",
                required: false,
                group: "디멘션",
                valueVocabulary: ["0", "1", "on", "off", "active", "inactive", "true", "false", "집행", "중단", "진행", "종료", "켜짐", "꺼짐"],
              },
              revenue_d0: {
                label: "매출 D0",
                aliases: ["rev_d0", "revenue0", "매출_d0"],
                type: "number",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              pu_d0: {
                label: "결제건수 D0",
                aliases: ["pu_cnt_d0", "purchase_d0", "결제_d0"],
                type: "number",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              ret_d0: {
                label: "잔존율 D0",
                aliases: ["retention_d0", "잔존_d0"],
                type: "percent",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              revenue_d7: {
                label: "매출 D7",
                aliases: ["rev_d7", "revenue7", "매출_d7"],
                type: "number",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              pu_d7: {
                label: "결제건수 D7",
                aliases: ["pu_cnt_d7", "purchase_d7", "결제_d7"],
                type: "number",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              ret_d7: {
                label: "잔존율 D7",
                aliases: ["retention_d7", "잔존_d7"],
                type: "percent",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              revenue_d14: {
                label: "매출 D14",
                aliases: ["rev_d14", "revenue14", "매출_d14"],
                type: "number",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              pu_d14: {
                label: "결제건수 D14",
                aliases: ["pu_cnt_d14", "purchase_d14", "결제_d14"],
                type: "number",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              ret_d14: {
                label: "잔존율 D14",
                aliases: ["retention_d14", "잔존_d14"],
                type: "percent",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              revenue_d30: {
                label: "매출 D30",
                aliases: ["rev_d30", "revenue30", "매출_d30"],
                type: "number",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              pu_d30: {
                label: "결제건수 D30",
                aliases: ["pu_cnt_d30", "purchase_d30", "결제_d30"],
                type: "number",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              ret_d30: {
                label: "잔존율 D30",
                aliases: ["retention_d30", "잔존_d30", "ret30", "r_d30"],
                type: "percent",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              revenue_d60: {
                label: "매출 D60",
                aliases: ["rev_d60", "revenue60", "매출_d60"],
                type: "number",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              pu_d60: {
                label: "결제건수 D60",
                aliases: ["pu_cnt_d60", "purchase_d60", "결제_d60"],
                type: "number",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              ret_d60: {
                label: "잔존율 D60",
                aliases: ["retention_d60", "잔존_d60", "ret60", "r_d60"],
                type: "percent",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              revenue_d90: {
                label: "매출 D90",
                aliases: ["rev_d90", "revenue90", "매출_d90"],
                type: "number",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              pu_d90: {
                label: "결제건수 D90",
                aliases: ["pu_cnt_d90", "purchase_d90", "결제_d90"],
                type: "number",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              ret_d90: {
                label: "잔존율 D90",
                aliases: ["retention_d90", "잔존_d90", "ret90", "r_d90"],
                type: "percent",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              revenue_d180: {
                label: "매출 D180",
                aliases: ["rev_d180", "revenue180", "매출_d180"],
                type: "number",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              pu_d180: {
                label: "결제건수 D180",
                aliases: ["pu_cnt_d180", "purchase_d180", "결제_d180"],
                type: "number",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              ret_d180: {
                label: "잔존율 D180",
                aliases: ["retention_d180", "잔존_d180", "ret180", "r_d180"],
                type: "percent",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              revenue_d360: {
                label: "매출 D360",
                aliases: ["rev_d360", "revenue360", "매출_d360"],
                type: "number",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              pu_d360: {
                label: "결제건수 D360",
                aliases: ["pu_cnt_d360", "purchase_d360", "결제_d360"],
                type: "number",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              ret_d360: {
                label: "잔존율 D360",
                aliases: ["retention_d360", "잔존_d360", "ret360", "r_d360"],
                type: "percent",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              // === Cannibalization Analyzer 전용 (5-5) ===
              paid_regs: {
                label: "유료 가입",
                aliases: [
                  "paid regs",
                  "paid signups",
                  "paid_signups",
                  "유료가입",
                  "유료_가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              organic_regs: {
                label: "오가닉 가입",
                aliases: [
                  "organic regs",
                  "organic signups",
                  "organic_signups",
                  "오가닉가입",
                  "유기적가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              total_regs: {
                label: "총 가입",
                aliases: [
                  "total regs",
                  "total signups",
                  "total_signups",
                  "총가입",
                  "전체 가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              paid_react: {
                label: "유료 재활성화",
                aliases: [
                  "paid react",
                  "paid reactivation",
                  "paid_reactivation",
                  "paid_reactivations",
                  "유료재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              organic_react: {
                label: "오가닉 재활성화",
                aliases: [
                  "organic react",
                  "organic reactivation",
                  "organic_reactivation",
                  "organic_reactivations",
                  "오가닉재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              total_react: {
                label: "총 재활성화",
                aliases: [
                  "total react",
                  "total reactivation",
                  "total_reactivation",
                  "총재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              // === Creative Analyzer 전용 (5-6) ===
              creative_id: {
                label: "소재ID",
                labelEn: "Creative ID",
                aliases: [
                  "creative",
                  "creative id",
                  "creative_name",
                  "creativename",
                  "크리에이티브id",
                  "크리에이티브명",
                  "소재",
                  "소재id",
                  "소재 id",
                  "소재명",
                  "소재이름",
                  "ad_name",
                  "adname",
                  "ad name",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              campaign_id: {
                label: "캠페인ID",
                aliases: [
                  "campaign id",
                  "campaign_name",
                  "campaignname",
                  "campaign name",
                  "캠페인id",
                  "캠페인명",
                  "캠페인이름",
                  "ad_set",
                  "adset",
                  "adset_name",
                  "adsetname",
                  "adgroup",
                  "adgroup_name",
                  "ad_group",
                  "ad_group_name",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              spend: {
                label: "비용(Creative)",
                labelEn: "Spend (creative)",
                // Meta 등 소재 성과 export의 실제 표시 헤더. `cost`에도 같은 별칭이
                // 있지만 도구 스코프가 9-6의 spend를 선택해 기존 엔진 키를 보존한다.
                aliases: ["광고비", "spend", "creative spend", "amount spent", "cost", "비용"],
                type: "number",
                required: false,
                group: "Creative",
              },
              audience_segment: {
                label: "오디언스 세그먼트",
                aliases: ["audience", "타겟", "오디언스", "segment"],
                type: "string",
                required: false,
                group: "Creative",
              },
              video_3s_views: {
                label: "3초 조회수",
                aliases: ["3sec views", "3초조회", "video 3s", "3s views"],
                type: "number",
                required: false,
                group: "Creative",
              },
              video_completions: {
                label: "영상 완료수",
                aliases: ["video completions", "완료수", "video complete"],
                type: "number",
                required: false,
                group: "Creative",
              },
              hook_type: {
                label: "Hook 유형",
                aliases: ["hook", "hook type", "훅", "훅유형"],
                type: "string",
                required: false,
                group: "Creative",
              },
              message_angle: {
                label: "메시지 앵글",
                aliases: ["message", "angle", "앵글", "메시지앵글"],
                type: "string",
                required: false,
                group: "Creative",
              },
              first_3s: {
                label: "첫 3초 컨셉",
                aliases: ["first 3s", "오프닝", "intro"],
                type: "string",
                required: false,
                group: "Creative",
              },
              format: {
                label: "포맷",
                aliases: ["creative format", "포맷", "ad format"],
                type: "string",
                required: false,
                group: "Creative",
              },
              has_text_overlay: {
                label: "텍스트 오버레이",
                aliases: ["text overlay", "has text", "오버레이"],
                type: "string",
                required: false,
                group: "Creative",
              },
              cta_style: {
                label: "CTA 스타일",
                aliases: ["cta", "cta style", "cta스타일"],
                type: "string",
                required: false,
                group: "Creative",
              },
              duration_bucket: {
                label: "영상 길이대",
                aliases: ["duration", "length", "길이대", "영상길이"],
                type: "string",
                required: false,
                group: "Creative",
              },
              duration_seconds: {
                label: "실제 영상 길이(초)",
                labelEn: "Video duration (seconds)",
                aliases: ["duration seconds", "duration_seconds", "video duration", "video_duration_seconds", "영상 길이 초", "영상길이초"],
                type: "number",
                required: false,
                group: "Creative",
              },
              text_length: {
                label: "화면 텍스트 글자수",
                labelEn: "On-screen text length",
                aliases: ["text length", "text_length", "ocr character count", "ocr_text_length", "텍스트 글자수", "자막 글자수"],
                type: "number",
                required: false,
                group: "Creative",
              },
              scene_cut_count: {
                label: "장면 전환수",
                labelEn: "Scene cut count",
                aliases: ["scene cut count", "scene_cut_count", "shot count", "cut count", "장면 전환수", "컷 수"],
                type: "number",
                required: false,
                group: "Creative",
              },
              face_screen_ratio: {
                label: "인물 화면 비율",
                labelEn: "Face screen ratio",
                aliases: ["face screen ratio", "face_screen_ratio", "face area ratio", "인물 화면 비율", "얼굴 비중"],
                type: "number",
                required: false,
                group: "Creative",
              },
              speech_rate: {
                label: "말하기 속도",
                labelEn: "Speech rate",
                aliases: ["speech rate", "speech_rate", "words per minute", "wpm", "말하기 속도", "발화 속도"],
                type: "number",
                required: false,
                group: "Creative",
              },
              creative_url: {
                label: "소재 링크(URL)",
                aliases: [
                  "url",
                  "link",
                  "creative_url",
                  "creative url",
                  "creative_link",
                  "ad_url",
                  "preview_url",
                  "소재url",
                  "소재 url",
                  "소재링크",
                  "링크",
                  "주소",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              // === Test Readout 전용 (5-7) ===
              experiment_id: {
                label: "실험ID",
                aliases: ["exp_id", "test_id", "실험id", "테스트id"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              arm_id: {
                label: "변형 그룹 (Arm)",
                aliases: ["arm", "group_id", "variant_id", "variant", "arm_id", "암id", "그룹id", "변형"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              arm_label: {
                label: "암 라벨",
                aliases: ["arm label", "variant", "암라벨", "그룹명"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              is_control: {
                label: "대조군 여부 (A/B)",
                labelEn: "Control flag (A/B)",
                aliases: ["control", "is control", "is_control", "대조군여부", "대조군"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              metric_tier: {
                label: "지표 단계",
                aliases: ["tier", "stage", "metric stage", "지표단계", "단계"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              metric_name: {
                label: "지표명",
                aliases: ["metric", "metric name", "지표"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              numerator: {
                label: "전환수 (분자)",
                labelEn: "Conversions (numerator)",
                aliases: ["num", "numerator", "conversions", "conv", "성공수", "전환수", "전환"],
                type: "number",
                required: false,
                group: "Test Readout",
              },
              denominator: {
                label: "그룹 인원·모수 (분모)",
                labelEn: "Sample size (denominator)",
                aliases: ["den", "denominator", "users", "exposures", "group_size", "전체수", "노출수", "인원", "모수"],
                type: "number",
                required: false,
                group: "Test Readout",
              },
              start_date: {
                label: "시작일",
                aliases: ["start", "start date", "시작일자"],
                type: "date",
                required: false,
                group: "Test Readout",
              },
              end_date: {
                label: "종료일",
                aliases: ["end", "end date", "종료일자"],
                type: "date",
                required: false,
                group: "Test Readout",
              },
              // === Incrementality / Holdout 전용 (5-15) ===
              holdout_group: {
                label: "노출/홀드아웃 구분",
                aliases: [
                  "holdout",
                  "holdout_group",
                  "group_type",
                  "test_control",
                  "exposed",
                  "exposed_control",
                  "노출그룹",
                  "홀드아웃",
                ],
                type: "string",
                required: false,
                group: "Incrementality",
              },
              // `group`만으로는 처리·대조군인지 일반 분류 차원인지 판별할 수 없다.
              // 따라서 이 키는 5-23의 명시적 역할 선택에서만 쓰이며, V2에서도
              // confirmation-required intervention_group으로만 승격한다.
              group: {
                label: "처리/대조 그룹",
                labelEn: "Treatment/control group",
                aliases: ["treatment_group", "treatment group", "experiment_group", "experiment group", "처리군", "대조군", "처리 대조군"],
                type: "string",
                required: false,
                group: "Incrementality",
              },
              // === Quality Analyzer 전용 (5-8) — 코호트 리텐션/LTV ===
              cohort_date: {
                label: "코호트 일자",
                aliases: [
                  "cohort",
                  "cohort_date",
                  "install_date",
                  "설치일",
                  "코호트일자",
                ],
                type: "date",
                required: false,
                group: "Quality",
              },
              day_offset: {
                label: "Day Offset",
                aliases: ["day", "d_offset", "day_n", "days_since_install"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_size: {
                label: "코호트 크기",
                aliases: [
                  "cohort_size",
                  "n_users",
                  "users",
                  "n_installs",
                  "초기사용자수",
                ],
                type: "number",
                required: false,
                group: "Quality",
              },
              retained_users: {
                label: "잔존 사용자수",
                aliases: ["retained", "retained_users", "active_users", "잔존수"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_revenue: {
                label: "코호트 매출",
                aliases: ["cohort_revenue", "cumulative_revenue", "revenue", "rev"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_payments: {
                label: "코호트 결제건수",
                aliases: [
                  "cohort_payments",
                  "payments",
                  "num_payments",
                  "payment_count",
                  "결제건수",
                ],
                type: "number",
                required: false,
                group: "Quality",
              },
              // === Marketing-Response Regression / MMM 전용 (5-18) — 주간 per-platform ===
              iso_week_start: {
                label: "ISO 주 시작일",
                aliases: ["iso_week_start", "week", "week_start", "주시작", "주"],
                type: "date",
                required: false,
                group: "MMR",
              },
              org_reg: {
                label: "Organic 가입",
                aliases: [
                  "org_reg",
                  "organic_reg",
                  "organic_registration",
                  "오가닉가입",
                ],
                type: "number",
                required: false,
                group: "MMR",
              },
              paid_reg_w: {
                label: "Paid 가입(주)",
                aliases: ["paid_reg", "paid_registration", "유료가입주"],
                type: "number",
                required: false,
                group: "MMR",
              },
              org_react: {
                label: "Organic 재활성",
                aliases: [
                  "org_react",
                  "organic_react",
                  "organic_reactivation",
                  "오가닉재활성",
                ],
                type: "number",
                required: false,
                group: "MMR",
              },
              paid_react_w: {
                label: "Paid 재활성(주)",
                aliases: ["paid_react", "paid_reactivation", "유료재활성주"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_g_roi: {
                label: "Spend Google ROI",
                aliases: ["spend_g_roi", "google_roi", "g_roi"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_g_cbua: {
                label: "Spend Google CBUA",
                aliases: ["spend_g_cbua", "google_cbua", "g_cbua", "cbua"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_meta: {
                label: "Spend Meta",
                aliases: ["spend_meta", "meta_spend", "facebook_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_tt: {
                label: "Spend TikTok",
                aliases: ["spend_tt", "tiktok_spend", "tt_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_brand: {
                label: "Spend Brand",
                aliases: ["spend_brand", "brand_spend", "브랜드"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_react: {
                label: "Spend React(증분검정)",
                aliases: ["spend_react", "paid_react_spend", "react_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              seollal: {
                label: "설날 주",
                aliases: ["seollal", "lny", "설날"],
                type: "number",
                required: false,
                group: "MMR",
              },
              chuseok: {
                label: "추석 주",
                aliases: ["chuseok", "추석"],
                type: "number",
                required: false,
                group: "MMR",
              },
              pre_lny: {
                label: "설날 전주",
                aliases: ["pre_lny", "pre_seollal"],
                type: "number",
                required: false,
                group: "MMR",
              },
              post_chuseok_wk: {
                label: "추석 후주",
                aliases: ["post_chuseok_wk", "post_chuseok_week"],
                type: "number",
                required: false,
                group: "MMR",
              },
              other_holiday: {
                label: "기타 공휴일 주",
                aliases: ["other_holiday", "holiday"],
                type: "number",
                required: false,
                group: "MMR",
              },
              post_chuseok_step: {
                label: "추석후 STEP",
                aliases: ["post_chuseok_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              line_signoff_step: {
                label: "LINE signoff STEP",
                aliases: ["line_signoff_step", "line_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              attr_change_step: {
                label: "어트리뷰션 변경 STEP",
                aliases: ["attr_change_step", "skan_step", "att_step", "mmp_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              // === MMM 방법론 (5-18) — 주간 패널 (week index 기반) ===
              week: {
                label: "주 인덱스(t)",
                aliases: ["t", "week", "week_index", "주", "주인덱스"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_reg: {
                label: "가입(Reg)",
                labelEn: "Registrations",
                aliases: ["Regs", "reg", "registrations", "가입"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_react: {
                label: "재활성(React)",
                labelEn: "Reactivations",
                aliases: ["React", "reactivation", "재활성"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_google_roi: {
                label: "Spend Google ROI",
                labelEn: "Spend Google ROI",
                aliases: ["G_ROI", "google_roi", "g_roi"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_google_cbua: {
                label: "Spend Google CBUA",
                labelEn: "Spend Google CBUA",
                aliases: ["G_CBUA", "google_cbua", "g_cbua"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_meta: {
                label: "Spend Meta",
                labelEn: "Spend Meta",
                aliases: ["Meta", "meta", "facebook"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_tiktok: {
                label: "Spend TikTok",
                labelEn: "Spend TikTok",
                aliases: ["TT", "tiktok", "tt"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_brand: {
                label: "Spend Brand",
                labelEn: "Spend Brand",
                aliases: ["Brand", "brand", "브랜드"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_prelny: {
                label: "PreLNY 더미",
                aliases: ["PreLNY", "pre_lny"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_seollal: {
                label: "Seollal 더미",
                aliases: ["Seollal", "seollal", "설날"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_chuseokonly: {
                label: "ChuseokOnly 더미",
                aliases: ["ChuseokOnly", "chuseok_only"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_postchuwk: {
                label: "PostChuWk 더미",
                aliases: ["PostChuWk", "post_chu_wk"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_otherhol: {
                label: "OtherHol 더미",
                aliases: ["OtherHol", "other_hol", "기타공휴일"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_platform: {
                label: "플랫폼(iOS/AOS)",
                aliases: ["platform", "os", "플랫폼", "platform_name"],
                type: "string",
                required: false,
                group: "MMM",
              },
            };

export const TOOL_REQUIRED_FIELDS = {
              // /start는 첫 업로드에서 효율 CSV의 기본 역할만 판별한다. 필드 스코프가
              // 비어 있으면 전체 STANDARD_FIELDS(브랜드 on/off 포함)로 폴백해 숫자열을
              // 잘못 잡을 수 있으므로, 시작 화면도 명시적인 계약을 가진다.
              "start-gate": ["date", "cost", { oneOf: ["installs", "actions"] }],
              "5-4": [
                "numerator",
                "denominator",
                { oneOf: ["is_control", "arm_id"] },
              ],
              "5-2": ["date", "cost", { oneOf: ["installs", "actions"] }],
              "5-3": [
                "date",
                "cost",
                { oneOf: ["channel", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-22": [
                "date",
                "cost",
                { oneOf: ["channel", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-5": ["date", "paid_regs", "organic_regs"],
              "5-6": [
                "creative_id",
                "date",
                "channel",
                "impressions",
                "clicks",
                "installs",
                "spend",
              ],
              "5-7": [
                "experiment_id",
                "arm_id",
                "is_control",
                "metric_tier",
                "metric_name",
                "numerator",
                "denominator",
              ],
              "5-8": [
                "cohort_date",
                "day_offset",
                "cohort_size",
                { oneOf: ["retained_users", "cohort_revenue"] },
              ],
              "5-9": [
                "date",
                "cost",
                { oneOf: ["installs", "actions"] },
                { oneOf: ["revenue_d0", "revenue_d7", "revenue_d14"] },
              ],
              "5-10": ["date", "cost"],
              "5-11": [
                "date",
                "impressions",
                "clicks",
                { oneOf: ["installs", "actions"] },
              ],
              "5-12": [
                "cost",
                { oneOf: ["channel", "country", "platform", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-13": ["date", "cost", { oneOf: ["installs", "actions"] }],
              "5-14": [
                "date",
                { oneOf: ["cost", "installs", "actions", "clicks", "impressions"] },
              ],
              "5-16": [
                "cost",
                {
                  oneOf: [
                    "revenue_d0",
                    "revenue_d7",
                    "revenue_d14",
                    "revenue_d30",
                    "revenue_d90",
                    "revenue_d180",
                    "revenue_d360",
                  ],
                },
              ],
              "5-15": ["holdout_group", "numerator", "denominator"],
              "5-18": [
                "week",
                { oneOf: ["mmm_reg", "mmm_react"] },
                {
                  oneOf: [
                    "ch_google_roi",
                    "ch_google_cbua",
                    "ch_meta",
                    "ch_tiktok",
                    "ch_brand",
                  ],
                },
              ],
              "5-21": [
                "date",
                { oneOf: ["spend", "cost"] },
                "channel",
                { oneOf: ["installs", "actions"] },
              ],
              "5-24": [
                "date",
                "campaign_on",
                { oneOf: ["brand_search", "direct_traffic", "installs", "actions"] },
              ],
              "5-25": ["date", "cost", { oneOf: ["channel", "campaign_name"] }],
              "5-27": ["date", "store_source", "product_page_views", "installs"],
              "5-26": ["date", "search_term", "cost", "clicks", { oneOf: ["installs", "actions"] }],
              // 구성 변화는 세그먼트 축이 사용자마다 달라 표준키로 고정할 수 없다.
              // 여기서는 기간만 계약으로 두고, 세그먼트·분석 단위·모수 역할은
              // 도구 안 SegmentRoleMapper가 원본 컬럼 이름 그대로 선언받는다
              // (전역 STANDARD_FIELDS에 사용자별 세그먼트를 계속 늘리지 않는다).
              "5-29": ["date"],
              // 핵심 액션 생존은 두 입력 경로를 지원한다. 기간+이탈 플래그 또는
              // 날짜 경로의 시작일과 (이벤트일 또는 관측 종료일)로 사건·중도
              // 절단을 복원한다. 날짜만으로 기간 기반 엔진 입력을 꾸며내지 않는다.
              "5-28": [
                { oneOf: ["tenure_periods", "subscription_start_date"] },
                { oneOf: ["event_observed", "churn_date", "observation_end_date"] },
              ],
              // 9-3 콘텐츠 트래픽 변동 — 5-21과 동일 엔진(pvmMath). 유입경로=channel·
              // 트래픽=installs(또는 actions)·제작/배포비=spend. 필드명은 엔진 계약이라
              // 5-21과 동일, 화면 라벨만 콘텐츠 도메인(유입경로/카테고리/콘텐츠).
              "9-3": [
                "date",
                "spend",
                "channel",
                { oneOf: ["installs", "actions"] },
              ],
              // 9-6 콘텐츠 신선도 진단 — 5-6과 동일 엔진(creativeMath). 콘텐츠=creative_id·
              // 배포채널=channel·전환=installs·제작배포비=spend. 필드명은 엔진 계약이라
              // 5-6과 동일, 화면 라벨만 콘텐츠 도메인(콘텐츠/신선도/발행).
              "9-6": [
                "creative_id",
                "date",
                "channel",
                "impressions",
                "clicks",
                "installs",
                "spend",
              ],
              // 9-7 콘텐츠 운영 대시보드 — 5-2와 동일 엔진(dashboardAggregator).
              // 트래픽 중심: 방문=installs, 구독=actions, 비용=cost. 매출·결제·리텐션은
              // 콘텐츠 데이터에 없어 필수/옵션 어디에도 두지 않음(§정직성).
              "9-7": ["date", "cost", { oneOf: ["installs", "actions"] }],
            };
export const TOOL_OPTIONAL_FIELDS = {
              // /start의 매핑은 효율 슬라이스에 그대로 저장돼 사이드바로 진입한
              // 도구가 이어 쓴다(추천 카드로 들어갈 때만 prepareDatasetForTool이
              // 재매핑). 그래서 스코프는 "효율 패밀리(5-2·5-21·5-22·5-3)가 쓰는
              // 필드의 합집합"이어야 하고, 여기서 빠진 컬럼은 사이드바 경로에서
              // 영구 미매핑이 된다. 브랜드·증분 전용 필드(campaign_on 등)는 계속
              // 제외한다 — 첫 업로드에서 판별할 근거가 없다.
              "start-gate": [
                { key: "snapshot_date", unlocks: "리텐션 Dn 마감 판정 — 데이터 추출 기준일" },
                { key: "channel", unlocks: "채널별 성과와 다음 분석 추천" },
                { key: "campaign_name", unlocks: "캠페인별 성과와 다음 분석 추천" },
                { key: "campaign_id", unlocks: "캠페인 단위 성과 변동 분석" },
                { key: "creative_id", unlocks: "소재별 성과 변동 분석" },
                { key: "creative_url", unlocks: "소재 미리보기 연결" },
                { key: "platform", unlocks: "OS별 성과 확인" },
                { key: "country", unlocks: "국가별 성과 확인" },
                { key: "source", unlocks: "유료·오가닉 분리" },
                { key: "impressions", unlocks: "노출·CTR·CPM 계산" },
                { key: "clicks", unlocks: "클릭·CTR·전환율(CVR) 계산" },
                { key: "revenue_d0", unlocks: "당일 매출·ROAS" },
                { key: "revenue_d7", unlocks: "ROAS·LTV 분석 추천" },
                { key: "revenue_d14", unlocks: "D14 매출 코호트" },
                { key: "pu_d7", unlocks: "결제건수 D7 코호트" },
                { key: "ret_d7", unlocks: "리텐션 D7 코호트" },
              ],
              "5-24": [
                { key: "cost", unlocks: "캠페인 투자 규모와 증분 성과를 함께 기록" },
                { key: "country", unlocks: "향후 지역 대조군 설계" },
                { key: "channel", unlocks: "브랜드 캠페인 매체 구분" },
              ],
              "5-25": [{ key: "campaign_name", unlocks: "채널 대신 캠페인 단위 공선성 점검" }],
              "5-27": [
                { key: "impressions", unlocks: "노출→제품페이지 통과율(탭률) 계산" },
                { key: "country", unlocks: "국가별 스토어 전환 비교" },
                { key: "event", unlocks: "그날 한 조치를 추이 차트에 세로선으로 표시" },
                { key: "event_type", unlocks: "이벤트 종류별 색 구분" },
              ],
              "5-26": [
                { key: "country", unlocks: "국가별 캠페인 예산·통화 분리" },
                { key: "campaign_name", unlocks: "캠페인별 조치 분리" },
                { key: "adgroup_name", unlocks: "광고그룹별 조치 분리" },
                { key: "match_type", unlocks: "Exact 승격 후보 판정" },
                { key: "daily_budget", unlocks: "캠페인 예산 대비 소진률" },
                { key: "target_cpa", unlocks: "성과 기준 CPT 조정" },
                { key: "target_cpt", unlocks: "CPT 권장값 기준" },
                { key: "current_cpt", unlocks: "현재 CPT에서 증감액 계산" },
              ],
              "5-29": [
                { key: "campaign_name", unlocks: "캠페인 간 볼륨 이동과 캠페인 내부 변화 분해" },
                { key: "channel", unlocks: "채널 단위 이동·내부 변화 분해" },
                { key: "platform", unlocks: "OS별로 섞이지 않게 비교 범위 분리" },
                { key: "country", unlocks: "국가별로 섞이지 않게 비교 범위 분리" },
                { key: "cost", unlocks: "구성 변화와 비용 흐름 함께 확인" },
              ],
              "5-28": [
                { key: "entry_period", unlocks: "관측 진입 시점이 다른 개체의 위험집합 보정" },
                { key: "channel", unlocks: "채널별 핵심 액션 생존 비교" },
                { key: "plan", unlocks: "플랜·제도별 관측 생존 비교" },
                { key: "promo", unlocks: "프로모션·처리별 관측 생존 비교" },
                { key: "event_type", unlocks: "이탈·종료 이벤트 유형을 원본 의미 그대로 보존" },
                { key: "cac", unlocks: "관측기간 반복 가치와 개체 획득·유지비 함께 확인" },
              ],
              "5-4": [
                { key: "is_control", unlocks: "대조군(Control) vs Test 판정" },
                { key: "arm_id", unlocks: "다변형 대량검정 (Variant A/B/C…)" },
                { key: "date", unlocks: "기간 표기 (선택)" },
              ],
              "5-2": [
                { key: "snapshot_date", unlocks: "리텐션 Dn 마감 판정 — 데이터 추출 기준일" },
                { key: "source", unlocks: "광고/오가닉(소스) 필터 — 유료·자연 유입 분리" },
                { key: "channel", unlocks: "채널별 비중·시계열 분석" },
                { key: "campaign_name", unlocks: "캠페인 단위 분석" },
                { key: "creative_id", unlocks: "소재별 성과 변동·피로도 분석 연결" },
                { key: "platform", unlocks: "OS 분포 시각화" },
                { key: "country", unlocks: "🗺 세그먼트 탭 — 국가 차원 분석" },
                {
                  key: "impressions",
                  unlocks: "🪜 퍼널 탭 — CTR/CPM 계산 (clicks와 함께)",
                },
                {
                  key: "clicks",
                  unlocks: "🪜 퍼널 탭 — CTR/CVR/CPC 계산 (impressions와 함께)",
                },
                { key: "actions", unlocks: "CPA·전환수 분석 (installs와 별도)" },
                {
                  key: "revenue_d0",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D0 매출/ROAS",
                },
                {
                  key: "revenue_d7",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D7 매출/ROAS",
                },
                {
                  key: "revenue_d14",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D14 매출/ROAS",
                },
                { key: "pu_d7", unlocks: "결제건수 D7 코호트" },
                { key: "ret_d7", unlocks: "리텐션 D7 코호트" },
              ],
              "5-3": [
                {
                  key: "country",
                  unlocks: "분석 단위 선택 (국가/채널/캠페인) + 국가 필터",
                },
                { key: "platform", unlocks: "OS 토글 (전체 / Android / iOS)" },
                {
                  key: "revenue_d7",
                  unlocks: "ROAS 시뮬레이션 + 분배 후 예상 매출 계산",
                },
                { key: "pu_d7", unlocks: "결제건수 기준 분배 (대안 metric)" },
                { key: "impressions", unlocks: "노출 기반 시뮬레이션" },
                { key: "clicks", unlocks: "클릭 기반 시뮬레이션" },
              ],
              "5-22": [
                {
                  key: "campaign_name",
                  unlocks: "분석 단위 '캠페인' 토글 — 캠페인별 포화도",
                },
                {
                  key: "revenue_d7",
                  unlocks: "ROAS 기준 포화도 (한계 ROAS vs 평균 ROAS)",
                },
                { key: "platform", unlocks: "OS(Android/iOS)별 행 분리" },
                { key: "actions", unlocks: "액션 기준 분석 (설치 대안)" },
              ],
              "5-5": [
                {
                  key: "total_regs",
                  unlocks: "Identity 일치 검증 (Total = Paid + Organic)",
                },
                { key: "paid_react", unlocks: "재활성화(React) 잠식 분석" },
                { key: "organic_react", unlocks: "재활성화(React) 잠식 분석" },
                { key: "total_react", unlocks: "React Identity 검증" },
                { key: "platform", unlocks: "OS 플랫폼 토글 (전체 / Android / iOS)" },
                { key: "cost", unlocks: "Tab D Efficiency (월별 CAC, 증분 효율)" },
                {
                  key: "channel",
                  unlocks: "채널별 sanity check (현재는 일별 aggregation)",
                },
              ],
              "5-6": [
                {
                  key: "campaign_id",
                  unlocks: "캠페인 fixed effect (decompose 안정성 ↑)",
                },
                {
                  key: "audience_segment",
                  unlocks: "Audience control + decompose 차원",
                },
                { key: "video_3s_views", unlocks: "Hook rate · 3초 retention 분해" },
                {
                  key: "video_completions",
                  unlocks: "Completion rate · 영상 끝까지 보는 비율",
                },
                { key: "hook_type", unlocks: "Decompose: Hook 유형별 효과" },
                {
                  key: "message_angle",
                  unlocks: "Decompose: 메시지 앵글별 효과 (Concept Matrix 행 기본)",
                },
                { key: "first_3s", unlocks: "Decompose: 오프닝 컨셉별 효과" },
                { key: "format", unlocks: "Decompose + Concept Matrix 열 기본" },
                {
                  key: "has_text_overlay",
                  unlocks: "Decompose: 텍스트 오버레이 유무 효과",
                },
                { key: "cta_style", unlocks: "Decompose: CTA 스타일별 효과" },
                { key: "duration_bucket", unlocks: "Decompose: 길이대별 효과" },
                { key: "duration_seconds", unlocks: "SVM: 실제 길이 기반 연속형 제작 특성" },
                { key: "text_length", unlocks: "SVM: 화면 텍스트 밀도 특성" },
                { key: "scene_cut_count", unlocks: "SVM: 장면 전환 빈도 특성" },
                { key: "face_screen_ratio", unlocks: "SVM: 인물 노출 비율 특성" },
                { key: "speech_rate", unlocks: "SVM: 발화 속도 특성" },
                {
                  key: "actions",
                  unlocks: "CPA decompose (installs 대신 액션 기준)",
                },
                { key: "revenue_d7", unlocks: "ROAS metric (분해 대상에 추가)" },
              ],
              "5-7": [
                { key: "arm_label", unlocks: "암 라벨 표시 (UI 가독성)" },
                { key: "start_date", unlocks: "실험 기간 표시" },
                { key: "end_date", unlocks: "실험 기간 표시" },
              ],
              "5-8": [
                { key: "channel", unlocks: "채널별 코호트 비교 분리" },
                { key: "country", unlocks: "국가별 코호트 비교 분리" },
                { key: "platform", unlocks: "OS별 코호트 비교 분리" },
                { key: "retained_users", unlocks: "리텐션 곡선 분석" },
                { key: "cohort_revenue", unlocks: "LTV 곡선 + 외삽 분석" },
                { key: "cohort_payments", unlocks: "PUR(결제건수) 곡선 + 외삽 분석" },
              ],
              "5-9": [
                { key: "channel", unlocks: "채널별 LTV:CAC 분리" },
                { key: "campaign_name", unlocks: "캠페인별 LTV:CAC" },
                { key: "country", unlocks: "국가별 분리" },
                { key: "platform", unlocks: "OS별 분리" },
                { key: "revenue_d0", unlocks: "D0 매출 (회수곡선 시작점)" },
                { key: "revenue_d7", unlocks: "D7 매출 (회수곡선)" },
                { key: "revenue_d14", unlocks: "D14 매출 (회수곡선·외삽)" },
                { key: "actions", unlocks: "CAC를 액션 기준으로 (installs 대신)" },
              ],
              "5-10": [
                { key: "channel", unlocks: "채널별 페이싱 분리" },
                { key: "installs", unlocks: "설치 페이싱·착지 예측" },
                { key: "actions", unlocks: "액션 페이싱" },
                { key: "revenue_d7", unlocks: "매출 페이싱" },
              ],
              "5-11": [
                { key: "channel", unlocks: "채널별 퍼널 분리" },
                { key: "country", unlocks: "국가별 퍼널" },
                { key: "platform", unlocks: "OS별 퍼널" },
                { key: "revenue_d7", unlocks: "매출 단계까지 퍼널 확장" },
                { key: "actions", unlocks: "액션 단계 (installs 다음)" },
              ],
              "5-12": [
                { key: "channel", unlocks: "채널 축" },
                { key: "country", unlocks: "국가 축" },
                { key: "platform", unlocks: "OS 축" },
                { key: "campaign_name", unlocks: "캠페인 드릴다운" },
                { key: "impressions", unlocks: "CTR/CPM 지표" },
                { key: "clicks", unlocks: "CTR/CVR 지표" },
                { key: "revenue_d7", unlocks: "ROAS 지표" },
                { key: "actions", unlocks: "CPA 지표" },
              ],
              "5-13": [
                { key: "impressions", unlocks: "CTR/CPM 카드" },
                { key: "clicks", unlocks: "CTR/CVR 카드" },
                { key: "actions", unlocks: "CPA 카드" },
                { key: "revenue_d7", unlocks: "ROAS 카드" },
                { key: "channel", unlocks: "(향후) 채널 분해" },
              ],
              "5-14": [
                { key: "channel", unlocks: "채널별 이상 분리 감지" },
                { key: "installs", unlocks: "설치·CVR 이상 감지" },
                { key: "actions", unlocks: "액션·CPA 이상 감지" },
                { key: "clicks", unlocks: "CTR 이상 감지" },
                { key: "impressions", unlocks: "노출·CPM 이상 감지" },
                { key: "revenue_d7", unlocks: "매출·ROAS 이상 감지" },
              ],
              "5-16": [
                { key: "channel", unlocks: "채널별 ROAS 성숙 분리" },
                { key: "campaign_name", unlocks: "캠페인별 성숙" },
                { key: "revenue_d0", unlocks: "D0 ROAS (성숙곡선 시작점)" },
                { key: "revenue_d7", unlocks: "D7 ROAS" },
                { key: "revenue_d14", unlocks: "D14 ROAS (외삽 정확도 ↑)" },
                {
                  key: "revenue_d30",
                  unlocks: "D30 ROAS (경험적 비율 anchor · 충분성 진단)",
                },
                { key: "revenue_d60", unlocks: "D60 ROAS (장기 곡선 정밀도 ↑)" },
                { key: "revenue_d90", unlocks: "D90 ROAS (실측 성숙 검증)" },
                { key: "revenue_d180", unlocks: "D180 ROAS (완전 성숙 기준)" },
                { key: "revenue_d360", unlocks: "D360 ROAS (연간 ROAS 실측)" },
              ],
              "5-15": [
                { key: "experiment_id", unlocks: "실험별 분리 readout" },
                { key: "spend", unlocks: "iROAS (증분 매출 / 비용)" },
                { key: "revenue_d7", unlocks: "증분 매출·iROAS" },
                { key: "arm_label", unlocks: "그룹 라벨 표시" },
              ],
              "5-18": [
                {
                  key: "mmm_platform",
                  unlocks: "플랫폼(iOS/AOS) 차원 — 상단 셀렉트로 세그먼트별 분석",
                },
                {
                  key: "mmm_react",
                  unlocks: "React 타깃 모델 (Reg와 별도 — 카니발 핵심)",
                },
                {
                  key: "ch_google_cbua",
                  unlocks: "Google CBUA 채널 (line_off와 공선 → 레짐 흡수)",
                },
                { key: "ch_meta", unlocks: "Meta 채널" },
                { key: "ch_tiktok", unlocks: "TikTok 채널" },
                {
                  key: "ch_brand",
                  unlocks: "Brand 채널 (강한 드라이버 — 포함 권장)",
                },
                { key: "d_prelny", unlocks: "설날 전주 더미" },
                { key: "d_seollal", unlocks: "설날 더미 (시트 audit)" },
                { key: "d_chuseokonly", unlocks: "추석 더미" },
                { key: "d_postchuwk", unlocks: "추석 후주 더미" },
                { key: "d_otherhol", unlocks: "기타 공휴일 더미" },
              ],
              "5-21": [
                {
                  key: "impressions",
                  unlocks: "효율 변화를 매체가(CPM)와 반응률로 분해 — 매핑 안 하면 물량·효율·믹스까지만 분해",
                },
                {
                  key: "campaign_id",
                  unlocks: "캠페인 단계 분해 — 매핑 안 하면 채널→소재 2단계로 동작",
                },
                {
                  key: "creative_id",
                  unlocks:
                    "소재 단계 딥다이브(§4) — 매핑 안 하면 채널/캠페인까지만 분해",
                },
                {
                  key: "creative_url",
                  unlocks:
                    "소재별 결과(§4)에 소재 링크 표시 — 클릭 시 새 창(merge 시 비용 최대 소재 URL)",
                },
                {
                  key: "impressions",
                  unlocks: "소재별 CTR 비교(§4) — clicks와 함께 매핑 시 활성화",
                },
                {
                  key: "clicks",
                  unlocks: "소재별 CTR 비교(§4) — impressions와 함께 매핑 시 활성화",
                },
              ],
              // 9-3 콘텐츠 트래픽 변동 — campaign_id=카테고리·creative_id=콘텐츠 단계.
              "9-3": [
                {
                  key: "campaign_id",
                  unlocks: "카테고리 단계 분해 — 매핑 안 하면 유입경로→콘텐츠 2단계로 동작",
                },
                {
                  key: "creative_id",
                  unlocks: "콘텐츠 단계 딥다이브(§4) — 매핑 안 하면 유입경로/카테고리까지만 분해",
                },
                {
                  key: "creative_url",
                  unlocks: "콘텐츠별 결과(§4)에 콘텐츠 링크 표시 — 클릭 시 새 창",
                },
                {
                  key: "impressions",
                  unlocks: "콘텐츠별 CTR 비교(§4) — clicks와 함께 매핑 시 활성화",
                },
                {
                  key: "clicks",
                  unlocks: "콘텐츠별 CTR 비교(§4) — impressions와 함께 매핑 시 활성화",
                },
              ],
              // 9-6 콘텐츠 신선도 진단 — 5-6과 동일 옵션(속성 컬럼 = 신선도/조합 분해).
              "9-6": [
                {
                  key: "campaign_id",
                  unlocks: "카테고리 fixed effect (decompose 안정성 ↑)",
                },
                {
                  key: "audience_segment",
                  unlocks: "독자 세그먼트 control + decompose 차원",
                },
                { key: "video_3s_views", unlocks: "Hook rate · 3초 retention 분해" },
                {
                  key: "video_completions",
                  unlocks: "Completion rate · 끝까지 보는 비율",
                },
                { key: "hook_type", unlocks: "Decompose: 후킹 유형별 효과" },
                {
                  key: "message_angle",
                  unlocks: "Decompose: 콘텐츠 앵글별 효과 (Concept Matrix 행 기본)",
                },
                { key: "first_3s", unlocks: "Decompose: 오프닝 컨셉별 효과" },
                { key: "format", unlocks: "Decompose + Concept Matrix 열 기본" },
                {
                  key: "has_text_overlay",
                  unlocks: "Decompose: 텍스트 오버레이 유무 효과",
                },
                { key: "cta_style", unlocks: "Decompose: CTA 스타일별 효과" },
                { key: "duration_bucket", unlocks: "Decompose: 길이대별 효과" },
                { key: "duration_seconds", unlocks: "SVM: 실제 길이 기반 연속형 제작 특성" },
                { key: "text_length", unlocks: "SVM: 화면 텍스트 밀도 특성" },
                { key: "scene_cut_count", unlocks: "SVM: 장면 전환 빈도 특성" },
                { key: "face_screen_ratio", unlocks: "SVM: 인물 노출 비율 특성" },
                { key: "speech_rate", unlocks: "SVM: 발화 속도 특성" },
                {
                  key: "actions",
                  unlocks: "전환당비용 decompose (installs 대신 액션 기준)",
                },
                { key: "revenue_d7", unlocks: "ROAS metric (분해 대상에 추가)" },
              ],
              // 9-7 콘텐츠 운영 대시보드 — 트래픽 중심 옵션. 매출·결제·리텐션(revenue/
              // pu/ret) 컬럼은 콘텐츠 데이터에 없어 노출하지 않음(§정직성, 날조 금지).
              "9-7": [
                { key: "source", unlocks: "광고/오가닉(소스) 필터 — 유료·자연 유입 분리" },
                { key: "channel", unlocks: "유입경로별 비중·방문당 비용 비교" },
                { key: "campaign_name", unlocks: "카테고리 단위 분석" },
                { key: "platform", unlocks: "디바이스(모바일/데스크톱) 분포" },
                { key: "impressions", unlocks: "반응률(CTR)·CPM 계산 (clicks와 함께)" },
                { key: "clicks", unlocks: "반응률(CTR)·방문 전환율(CVR) 계산" },
                { key: "actions", unlocks: "구독당 비용·전환수 분석 (방문과 별도)" },
              ],
            };

// 구 5-18 안에 있던 다섯 분석(추세·변화맵·잠식·기여도·예측)은 같은 주간 패널
// CSV 하나를 공유한다. 계약을 다섯 번 베껴 쓰면 한 곳만 고쳐져 어긋나므로 허브
// 계약에서 **파생**한다(§7 — 목록을 두 곳에 나열하지 말 것).
export const RESPONSE_PANEL_TOOL_IDS = ["5-18-trend", "5-18-paid-organic", "5-18-cannibal", "5-18-mmm", "5-18-forecast"];
for (const id of RESPONSE_PANEL_TOOL_IDS) {
  TOOL_REQUIRED_FIELDS[id] = TOOL_REQUIRED_FIELDS["5-18"];
  TOOL_OPTIONAL_FIELDS[id] = TOOL_OPTIONAL_FIELDS["5-18"];
}

// CSV 헤더 배열 → {header: 표준필드키|"__ignore__"} 자동매핑. CsvUploader의 CSV 업로드
// 경로와 구글 시트 임포트 경로가 동일 로직을 공유하도록 추출(원래 CsvUploader.jsx
// processFile 내부에 있던 걸 이관 — 로직 변경 없음, 재사용을 위한 위치 이동만).
export function autoMapHeaders(headers, rows = [], allowedKeys) {
  return scoreMappingCandidates({ headers, rows, allowedKeys, fields: STANDARD_FIELDS }).selections;
}

// 숫자로 해석되는 표준 필드 키 집합. STANDARD_FIELDS에서 **파생**한다 — 손으로 나열하면
// 새 지표를 추가할 때 한쪽만 갱신돼 조용히 어긋난다(§7 "목록을 두 곳에 나열하지 말 것").
// percent는 제외: "%" 해석은 소비처 계약이라 여기서 정규화하면 의미가 바뀐다.
export const NUMERIC_STANDARD_KEYS = new Set(
  Object.entries(STANDARD_FIELDS)
    .filter(([, field]) => field?.type === "number")
    .map(([key]) => key),
);
