export const STANDARD_FIELDS = {
              date: {
                label: "날짜",
                aliases: ["dt", "날짜", "event_date", "day"],
                type: "date",
                required: true,
                group: "디멘션",
              },
              platform: {
                label: "플랫폼(OS)",
                aliases: ["os", "platform_name", "플랫폼"],
                type: "enum",
                required: false,
                group: "디멘션",
              },
              channel: {
                label: "채널/매체",
                aliases: ["network", "source", "media", "매체", "채널"],
                type: "string",
                required: false,
                group: "디멘션",
                oneOfGroup: "grouping",
              },
              campaign_name: {
                label: "캠페인명",
                aliases: ["campaign", "캠페인", "캠페인명"],
                type: "string",
                required: false,
                group: "디멘션",
                oneOfGroup: "grouping",
              },
              country: {
                label: "국가",
                aliases: ["country", "mkt_country", "국가", "country_code", "마켓"],
                type: "string",
                required: false,
                group: "디멘션",
              },
              cost: {
                label: "비용",
                aliases: ["spend", "비용", "광고비"],
                type: "number",
                required: true,
                group: "단일 지표",
              },
              impressions: {
                label: "노출수",
                aliases: ["imp", "impression", "노출"],
                type: "number",
                required: false,
                group: "단일 지표",
              },
              clicks: {
                label: "클릭수",
                aliases: ["click", "클릭"],
                type: "number",
                required: false,
                group: "단일 지표",
              },
              installs: {
                label: "설치수",
                aliases: ["install", "설치", "inst"],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "outcome",
              },
              actions: {
                label: "액션/가입 수",
                aliases: [
                  "action",
                  "actions",
                  "conversions",
                  "events",
                  "전환",
                  "액션",
                  "가입",
                  "가입수",
                  "가입 수",
                  "signup",
                  "signups",
                  "sign_up",
                  "sign_ups",
                  "registration",
                  "registrations",
                  "regs",
                  "reg",
                ],
                type: "number",
                required: false,
                group: "단일 지표",
                oneOfGroup: "outcome",
              },
              revenue_d0: {
                label: "매출 D0",
                aliases: ["rev_d0", "revenue0", "매출_d0"],
                type: "number",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              pu_d0: {
                label: "결제건수 D0",
                aliases: ["pu_cnt_d0", "purchase_d0", "결제_d0"],
                type: "number",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              ret_d0: {
                label: "잔존율 D0",
                aliases: ["retention_d0", "잔존_d0"],
                type: "percent",
                required: false,
                group: "코호트 D0",
                cohort: 0,
              },
              revenue_d7: {
                label: "매출 D7",
                aliases: ["rev_d7", "revenue7", "매출_d7"],
                type: "number",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              pu_d7: {
                label: "결제건수 D7",
                aliases: ["pu_cnt_d7", "purchase_d7", "결제_d7"],
                type: "number",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              ret_d7: {
                label: "잔존율 D7",
                aliases: ["retention_d7", "잔존_d7"],
                type: "percent",
                required: false,
                group: "코호트 D7",
                cohort: 7,
              },
              revenue_d14: {
                label: "매출 D14",
                aliases: ["rev_d14", "revenue14", "매출_d14"],
                type: "number",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              pu_d14: {
                label: "결제건수 D14",
                aliases: ["pu_cnt_d14", "purchase_d14", "결제_d14"],
                type: "number",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              ret_d14: {
                label: "잔존율 D14",
                aliases: ["retention_d14", "잔존_d14"],
                type: "percent",
                required: false,
                group: "코호트 D14",
                cohort: 14,
              },
              revenue_d30: {
                label: "매출 D30",
                aliases: ["rev_d30", "revenue30", "매출_d30"],
                type: "number",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              pu_d30: {
                label: "결제건수 D30",
                aliases: ["pu_cnt_d30", "purchase_d30", "결제_d30"],
                type: "number",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              ret_d30: {
                label: "잔존율 D30",
                aliases: ["retention_d30", "잔존_d30", "ret30", "r_d30"],
                type: "percent",
                required: false,
                group: "코호트 D30",
                cohort: 30,
              },
              revenue_d60: {
                label: "매출 D60",
                aliases: ["rev_d60", "revenue60", "매출_d60"],
                type: "number",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              pu_d60: {
                label: "결제건수 D60",
                aliases: ["pu_cnt_d60", "purchase_d60", "결제_d60"],
                type: "number",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              ret_d60: {
                label: "잔존율 D60",
                aliases: ["retention_d60", "잔존_d60", "ret60", "r_d60"],
                type: "percent",
                required: false,
                group: "코호트 D60",
                cohort: 60,
              },
              revenue_d90: {
                label: "매출 D90",
                aliases: ["rev_d90", "revenue90", "매출_d90"],
                type: "number",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              pu_d90: {
                label: "결제건수 D90",
                aliases: ["pu_cnt_d90", "purchase_d90", "결제_d90"],
                type: "number",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              ret_d90: {
                label: "잔존율 D90",
                aliases: ["retention_d90", "잔존_d90", "ret90", "r_d90"],
                type: "percent",
                required: false,
                group: "코호트 D90",
                cohort: 90,
              },
              revenue_d180: {
                label: "매출 D180",
                aliases: ["rev_d180", "revenue180", "매출_d180"],
                type: "number",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              pu_d180: {
                label: "결제건수 D180",
                aliases: ["pu_cnt_d180", "purchase_d180", "결제_d180"],
                type: "number",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              ret_d180: {
                label: "잔존율 D180",
                aliases: ["retention_d180", "잔존_d180", "ret180", "r_d180"],
                type: "percent",
                required: false,
                group: "코호트 D180",
                cohort: 180,
              },
              revenue_d360: {
                label: "매출 D360",
                aliases: ["rev_d360", "revenue360", "매출_d360"],
                type: "number",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              pu_d360: {
                label: "결제건수 D360",
                aliases: ["pu_cnt_d360", "purchase_d360", "결제_d360"],
                type: "number",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              ret_d360: {
                label: "잔존율 D360",
                aliases: ["retention_d360", "잔존_d360", "ret360", "r_d360"],
                type: "percent",
                required: false,
                group: "코호트 D360",
                cohort: 360,
              },
              // === Cannibalization Analyzer 전용 (5-5) ===
              paid_regs: {
                label: "유료 가입",
                aliases: [
                  "paid regs",
                  "paid signups",
                  "paid_signups",
                  "유료가입",
                  "유료_가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              organic_regs: {
                label: "오가닉 가입",
                aliases: [
                  "organic regs",
                  "organic signups",
                  "organic_signups",
                  "오가닉가입",
                  "유기적가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              total_regs: {
                label: "총 가입",
                aliases: [
                  "total regs",
                  "total signups",
                  "total_signups",
                  "총가입",
                  "전체 가입",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              paid_react: {
                label: "유료 재활성화",
                aliases: [
                  "paid react",
                  "paid reactivation",
                  "paid_reactivation",
                  "paid_reactivations",
                  "유료재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              organic_react: {
                label: "오가닉 재활성화",
                aliases: [
                  "organic react",
                  "organic reactivation",
                  "organic_reactivation",
                  "organic_reactivations",
                  "오가닉재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              total_react: {
                label: "총 재활성화",
                aliases: [
                  "total react",
                  "total reactivation",
                  "total_reactivation",
                  "총재활성화",
                ],
                type: "number",
                required: false,
                group: "Cannibalization",
              },
              // === Creative Analyzer 전용 (5-6) ===
              creative_id: {
                label: "소재ID",
                aliases: [
                  "creative",
                  "creative id",
                  "creative_name",
                  "creativename",
                  "크리에이티브id",
                  "크리에이티브명",
                  "소재",
                  "소재명",
                  "소재이름",
                  "ad_name",
                  "adname",
                  "ad name",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              campaign_id: {
                label: "캠페인ID",
                aliases: [
                  "campaign id",
                  "campaign_name",
                  "campaignname",
                  "campaign name",
                  "캠페인id",
                  "캠페인명",
                  "캠페인이름",
                  "ad_set",
                  "adset",
                  "adset_name",
                  "adsetname",
                  "adgroup",
                  "adgroup_name",
                  "ad_group",
                  "ad_group_name",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              spend: {
                label: "비용(Creative)",
                aliases: ["광고비", "spend", "creative spend", "cost", "비용"],
                type: "number",
                required: false,
                group: "Creative",
              },
              audience_segment: {
                label: "오디언스 세그먼트",
                aliases: ["audience", "타겟", "오디언스", "segment"],
                type: "string",
                required: false,
                group: "Creative",
              },
              video_3s_views: {
                label: "3초 조회수",
                aliases: ["3sec views", "3초조회", "video 3s", "3s views"],
                type: "number",
                required: false,
                group: "Creative",
              },
              video_completions: {
                label: "영상 완료수",
                aliases: ["video completions", "완료수", "video complete"],
                type: "number",
                required: false,
                group: "Creative",
              },
              hook_type: {
                label: "Hook 유형",
                aliases: ["hook", "hook type", "훅", "훅유형"],
                type: "string",
                required: false,
                group: "Creative",
              },
              message_angle: {
                label: "메시지 앵글",
                aliases: ["message", "angle", "앵글", "메시지앵글"],
                type: "string",
                required: false,
                group: "Creative",
              },
              first_3s: {
                label: "첫 3초 컨셉",
                aliases: ["first 3s", "오프닝", "intro"],
                type: "string",
                required: false,
                group: "Creative",
              },
              format: {
                label: "포맷",
                aliases: ["creative format", "포맷", "ad format"],
                type: "string",
                required: false,
                group: "Creative",
              },
              has_text_overlay: {
                label: "텍스트 오버레이",
                aliases: ["text overlay", "has text", "오버레이"],
                type: "string",
                required: false,
                group: "Creative",
              },
              cta_style: {
                label: "CTA 스타일",
                aliases: ["cta", "cta style", "cta스타일"],
                type: "string",
                required: false,
                group: "Creative",
              },
              duration_bucket: {
                label: "영상 길이대",
                aliases: ["duration", "length", "길이대", "영상길이"],
                type: "string",
                required: false,
                group: "Creative",
              },
              creative_url: {
                label: "소재 링크(URL)",
                aliases: [
                  "url",
                  "link",
                  "creative_url",
                  "creative url",
                  "creative_link",
                  "ad_url",
                  "preview_url",
                  "소재url",
                  "소재 url",
                  "소재링크",
                  "링크",
                  "주소",
                ],
                type: "string",
                required: false,
                group: "Creative",
              },
              // === Test Readout 전용 (5-7) ===
              experiment_id: {
                label: "실험ID",
                aliases: ["exp_id", "test_id", "실험id", "테스트id"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              arm_id: {
                label: "암ID",
                aliases: ["arm", "group_id", "variant_id", "암id", "그룹id"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              arm_label: {
                label: "암 라벨",
                aliases: ["arm label", "variant", "암라벨", "그룹명"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              is_control: {
                label: "대조군 여부",
                aliases: ["control", "is control", "대조군여부", "대조군"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              metric_tier: {
                label: "지표 단계",
                aliases: ["tier", "stage", "metric stage", "지표단계", "단계"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              metric_name: {
                label: "지표명",
                aliases: ["metric", "metric name", "지표"],
                type: "string",
                required: false,
                group: "Test Readout",
              },
              numerator: {
                label: "분자",
                aliases: ["num", "numerator", "성공수"],
                type: "number",
                required: false,
                group: "Test Readout",
              },
              denominator: {
                label: "분모",
                aliases: ["den", "denominator", "전체수", "노출수"],
                type: "number",
                required: false,
                group: "Test Readout",
              },
              start_date: {
                label: "시작일",
                aliases: ["start", "start date", "시작일자"],
                type: "date",
                required: false,
                group: "Test Readout",
              },
              end_date: {
                label: "종료일",
                aliases: ["end", "end date", "종료일자"],
                type: "date",
                required: false,
                group: "Test Readout",
              },
              // === Incrementality / Holdout 전용 (5-15) ===
              holdout_group: {
                label: "Holdout 그룹",
                aliases: [
                  "holdout",
                  "holdout_group",
                  "group_type",
                  "test_control",
                  "노출그룹",
                  "홀드아웃",
                ],
                type: "string",
                required: false,
                group: "Incrementality",
              },
              // === Quality Analyzer 전용 (5-8) — 코호트 리텐션/LTV ===
              cohort_date: {
                label: "코호트 일자",
                aliases: [
                  "cohort",
                  "cohort_date",
                  "install_date",
                  "설치일",
                  "코호트일자",
                ],
                type: "date",
                required: false,
                group: "Quality",
              },
              day_offset: {
                label: "Day Offset",
                aliases: ["day", "d_offset", "day_n", "days_since_install"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_size: {
                label: "코호트 크기",
                aliases: [
                  "cohort_size",
                  "n_users",
                  "users",
                  "n_installs",
                  "초기사용자수",
                ],
                type: "number",
                required: false,
                group: "Quality",
              },
              retained_users: {
                label: "잔존 사용자수",
                aliases: ["retained", "retained_users", "active_users", "잔존수"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_revenue: {
                label: "코호트 매출",
                aliases: ["cohort_revenue", "cumulative_revenue", "revenue", "rev"],
                type: "number",
                required: false,
                group: "Quality",
              },
              cohort_payments: {
                label: "코호트 결제건수",
                aliases: [
                  "cohort_payments",
                  "payments",
                  "num_payments",
                  "payment_count",
                  "결제건수",
                ],
                type: "number",
                required: false,
                group: "Quality",
              },
              // === Marketing-Response Regression / MMM 전용 (5-18) — 주간 per-platform ===
              iso_week_start: {
                label: "ISO 주 시작일",
                aliases: ["iso_week_start", "week", "week_start", "주시작", "주"],
                type: "date",
                required: false,
                group: "MMR",
              },
              org_reg: {
                label: "Organic 가입",
                aliases: [
                  "org_reg",
                  "organic_reg",
                  "organic_registration",
                  "오가닉가입",
                ],
                type: "number",
                required: false,
                group: "MMR",
              },
              paid_reg_w: {
                label: "Paid 가입(주)",
                aliases: ["paid_reg", "paid_registration", "유료가입주"],
                type: "number",
                required: false,
                group: "MMR",
              },
              org_react: {
                label: "Organic 재활성",
                aliases: [
                  "org_react",
                  "organic_react",
                  "organic_reactivation",
                  "오가닉재활성",
                ],
                type: "number",
                required: false,
                group: "MMR",
              },
              paid_react_w: {
                label: "Paid 재활성(주)",
                aliases: ["paid_react", "paid_reactivation", "유료재활성주"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_g_roi: {
                label: "Spend Google ROI",
                aliases: ["spend_g_roi", "google_roi", "g_roi"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_g_cbua: {
                label: "Spend Google CBUA",
                aliases: ["spend_g_cbua", "google_cbua", "g_cbua", "cbua"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_meta: {
                label: "Spend Meta",
                aliases: ["spend_meta", "meta_spend", "facebook_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_tt: {
                label: "Spend TikTok",
                aliases: ["spend_tt", "tiktok_spend", "tt_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_brand: {
                label: "Spend Brand",
                aliases: ["spend_brand", "brand_spend", "브랜드"],
                type: "number",
                required: false,
                group: "MMR",
              },
              spend_react: {
                label: "Spend React(증분검정)",
                aliases: ["spend_react", "paid_react_spend", "react_spend"],
                type: "number",
                required: false,
                group: "MMR",
              },
              seollal: {
                label: "설날 주",
                aliases: ["seollal", "lny", "설날"],
                type: "number",
                required: false,
                group: "MMR",
              },
              chuseok: {
                label: "추석 주",
                aliases: ["chuseok", "추석"],
                type: "number",
                required: false,
                group: "MMR",
              },
              pre_lny: {
                label: "설날 전주",
                aliases: ["pre_lny", "pre_seollal"],
                type: "number",
                required: false,
                group: "MMR",
              },
              post_chuseok_wk: {
                label: "추석 후주",
                aliases: ["post_chuseok_wk", "post_chuseok_week"],
                type: "number",
                required: false,
                group: "MMR",
              },
              other_holiday: {
                label: "기타 공휴일 주",
                aliases: ["other_holiday", "holiday"],
                type: "number",
                required: false,
                group: "MMR",
              },
              post_chuseok_step: {
                label: "추석후 STEP",
                aliases: ["post_chuseok_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              line_signoff_step: {
                label: "LINE signoff STEP",
                aliases: ["line_signoff_step", "line_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              attr_change_step: {
                label: "어트리뷰션 변경 STEP",
                aliases: ["attr_change_step", "skan_step", "att_step", "mmp_step"],
                type: "number",
                required: false,
                group: "MMR",
              },
              // === MMM 방법론 (5-18) — 주간 패널 (week index 기반) ===
              week: {
                label: "주 인덱스(t)",
                aliases: ["t", "week", "week_index", "주", "주인덱스"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_reg: {
                label: "가입(Reg)",
                aliases: ["Regs", "reg", "registrations", "가입"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_react: {
                label: "재활성(React)",
                aliases: ["React", "reactivation", "재활성"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_google_roi: {
                label: "Spend Google ROI",
                aliases: ["G_ROI", "google_roi", "g_roi"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_google_cbua: {
                label: "Spend Google CBUA",
                aliases: ["G_CBUA", "google_cbua", "g_cbua"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_meta: {
                label: "Spend Meta",
                aliases: ["Meta", "meta", "facebook"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_tiktok: {
                label: "Spend TikTok",
                aliases: ["TT", "tiktok", "tt"],
                type: "number",
                required: false,
                group: "MMM",
              },
              ch_brand: {
                label: "Spend Brand",
                aliases: ["Brand", "brand", "브랜드"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_prelny: {
                label: "PreLNY 더미",
                aliases: ["PreLNY", "pre_lny"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_seollal: {
                label: "Seollal 더미",
                aliases: ["Seollal", "seollal", "설날"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_chuseokonly: {
                label: "ChuseokOnly 더미",
                aliases: ["ChuseokOnly", "chuseok_only"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_postchuwk: {
                label: "PostChuWk 더미",
                aliases: ["PostChuWk", "post_chu_wk"],
                type: "number",
                required: false,
                group: "MMM",
              },
              d_otherhol: {
                label: "OtherHol 더미",
                aliases: ["OtherHol", "other_hol", "기타공휴일"],
                type: "number",
                required: false,
                group: "MMM",
              },
              mmm_platform: {
                label: "플랫폼(iOS/AOS)",
                aliases: ["platform", "os", "플랫폼", "platform_name"],
                type: "string",
                required: false,
                group: "MMM",
              },
            };

export const TOOL_REQUIRED_FIELDS = {
              "5-2": ["date", { oneOf: ["installs", "actions", "cost"] }],
              "5-3": [
                "date",
                "cost",
                { oneOf: ["channel", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-22": [
                "date",
                "cost",
                { oneOf: ["channel", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-5": ["date", "paid_regs", "organic_regs"],
              "5-6": [
                "creative_id",
                "date",
                "channel",
                "impressions",
                "clicks",
                "installs",
                "spend",
              ],
              "5-7": [
                "experiment_id",
                "arm_id",
                "is_control",
                "metric_tier",
                "metric_name",
                "numerator",
                "denominator",
              ],
              "5-8": [
                "cohort_date",
                "day_offset",
                "cohort_size",
                { oneOf: ["retained_users", "cohort_revenue"] },
              ],
              "5-9": [
                "date",
                "cost",
                { oneOf: ["installs", "actions"] },
                { oneOf: ["revenue_d0", "revenue_d7", "revenue_d14"] },
              ],
              "5-10": ["date", "cost"],
              "5-11": [
                "date",
                "impressions",
                "clicks",
                { oneOf: ["installs", "actions"] },
              ],
              "5-12": [
                "cost",
                { oneOf: ["channel", "country", "platform", "campaign_name"] },
                { oneOf: ["installs", "actions"] },
              ],
              "5-13": ["date", "cost", { oneOf: ["installs", "actions"] }],
              "5-14": [
                "date",
                { oneOf: ["cost", "installs", "actions", "clicks", "impressions"] },
              ],
              "5-16": [
                "cost",
                {
                  oneOf: [
                    "revenue_d0",
                    "revenue_d7",
                    "revenue_d14",
                    "revenue_d30",
                    "revenue_d90",
                    "revenue_d180",
                    "revenue_d360",
                  ],
                },
              ],
              "5-15": ["holdout_group", "numerator", "denominator"],
              "5-18": [
                "week",
                { oneOf: ["mmm_reg", "mmm_react"] },
                {
                  oneOf: [
                    "ch_google_roi",
                    "ch_google_cbua",
                    "ch_meta",
                    "ch_tiktok",
                    "ch_brand",
                  ],
                },
              ],
              "5-21": [
                "date",
                "spend",
                "channel",
                { oneOf: ["installs", "actions"] },
              ],
            };
export const TOOL_OPTIONAL_FIELDS = {
              "5-2": [
                { key: "channel", unlocks: "채널별 비중·시계열 분석" },
                { key: "campaign_name", unlocks: "캠페인 단위 분석" },
                { key: "platform", unlocks: "OS 분포 시각화" },
                { key: "country", unlocks: "🗺 세그먼트 탭 — 국가 차원 분석" },
                {
                  key: "impressions",
                  unlocks: "🪜 퍼널 탭 — CTR/CPM 계산 (clicks와 함께)",
                },
                {
                  key: "clicks",
                  unlocks: "🪜 퍼널 탭 — CTR/CVR/CPC 계산 (impressions와 함께)",
                },
                { key: "actions", unlocks: "CPA·전환수 분석 (installs와 별도)" },
                {
                  key: "revenue_d0",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D0 매출/ROAS",
                },
                {
                  key: "revenue_d7",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D7 매출/ROAS",
                },
                {
                  key: "revenue_d14",
                  unlocks: "💵 LTV:CAC 탭 · 📊 ROAS 성숙도 탭 — D14 매출/ROAS",
                },
                { key: "pu_d7", unlocks: "결제건수 D7 코호트" },
                { key: "ret_d7", unlocks: "리텐션 D7 코호트" },
              ],
              "5-3": [
                {
                  key: "country",
                  unlocks: "분석 단위 선택 (국가/채널/캠페인) + 국가 필터",
                },
                { key: "platform", unlocks: "OS 토글 (전체 / Android / iOS)" },
                {
                  key: "revenue_d7",
                  unlocks: "ROAS 시뮬레이션 + 분배 후 예상 매출 계산",
                },
                { key: "pu_d7", unlocks: "결제건수 기준 분배 (대안 metric)" },
                { key: "impressions", unlocks: "노출 기반 시뮬레이션" },
                { key: "clicks", unlocks: "클릭 기반 시뮬레이션" },
              ],
              "5-22": [
                {
                  key: "campaign_name",
                  unlocks: "분석 단위 '캠페인' 토글 — 캠페인별 포화도",
                },
                {
                  key: "revenue_d7",
                  unlocks: "ROAS 기준 포화도 (한계 ROAS vs 평균 ROAS)",
                },
                { key: "platform", unlocks: "OS(Android/iOS)별 행 분리" },
                { key: "actions", unlocks: "액션 기준 분석 (설치 대안)" },
              ],
              "5-5": [
                {
                  key: "total_regs",
                  unlocks: "Identity 일치 검증 (Total = Paid + Organic)",
                },
                { key: "paid_react", unlocks: "재활성화(React) 잠식 분석" },
                { key: "organic_react", unlocks: "재활성화(React) 잠식 분석" },
                { key: "total_react", unlocks: "React Identity 검증" },
                { key: "platform", unlocks: "OS 플랫폼 토글 (전체 / Android / iOS)" },
                { key: "cost", unlocks: "Tab D Efficiency (월별 CAC, 증분 효율)" },
                {
                  key: "channel",
                  unlocks: "채널별 sanity check (현재는 일별 aggregation)",
                },
              ],
              "5-6": [
                {
                  key: "campaign_id",
                  unlocks: "캠페인 fixed effect (decompose 안정성 ↑)",
                },
                {
                  key: "audience_segment",
                  unlocks: "Audience control + decompose 차원",
                },
                { key: "video_3s_views", unlocks: "Hook rate · 3초 retention 분해" },
                {
                  key: "video_completions",
                  unlocks: "Completion rate · 영상 끝까지 보는 비율",
                },
                { key: "hook_type", unlocks: "Decompose: Hook 유형별 효과" },
                {
                  key: "message_angle",
                  unlocks: "Decompose: 메시지 앵글별 효과 (Concept Matrix 행 기본)",
                },
                { key: "first_3s", unlocks: "Decompose: 오프닝 컨셉별 효과" },
                { key: "format", unlocks: "Decompose + Concept Matrix 열 기본" },
                {
                  key: "has_text_overlay",
                  unlocks: "Decompose: 텍스트 오버레이 유무 효과",
                },
                { key: "cta_style", unlocks: "Decompose: CTA 스타일별 효과" },
                { key: "duration_bucket", unlocks: "Decompose: 길이대별 효과" },
                {
                  key: "actions",
                  unlocks: "CPA decompose (installs 대신 액션 기준)",
                },
                { key: "revenue_d7", unlocks: "ROAS metric (분해 대상에 추가)" },
              ],
              "5-7": [
                { key: "arm_label", unlocks: "암 라벨 표시 (UI 가독성)" },
                { key: "start_date", unlocks: "실험 기간 표시" },
                { key: "end_date", unlocks: "실험 기간 표시" },
              ],
              "5-8": [
                { key: "channel", unlocks: "채널별 코호트 비교 분리" },
                { key: "country", unlocks: "국가별 코호트 비교 분리" },
                { key: "platform", unlocks: "OS별 코호트 비교 분리" },
                { key: "retained_users", unlocks: "리텐션 곡선 분석" },
                { key: "cohort_revenue", unlocks: "LTV 곡선 + 외삽 분석" },
                { key: "cohort_payments", unlocks: "PUR(결제건수) 곡선 + 외삽 분석" },
              ],
              "5-9": [
                { key: "channel", unlocks: "채널별 LTV:CAC 분리" },
                { key: "campaign_name", unlocks: "캠페인별 LTV:CAC" },
                { key: "country", unlocks: "국가별 분리" },
                { key: "platform", unlocks: "OS별 분리" },
                { key: "revenue_d0", unlocks: "D0 매출 (회수곡선 시작점)" },
                { key: "revenue_d7", unlocks: "D7 매출 (회수곡선)" },
                { key: "revenue_d14", unlocks: "D14 매출 (회수곡선·외삽)" },
                { key: "actions", unlocks: "CAC를 액션 기준으로 (installs 대신)" },
              ],
              "5-10": [
                { key: "channel", unlocks: "채널별 페이싱 분리" },
                { key: "installs", unlocks: "설치 페이싱·착지 예측" },
                { key: "actions", unlocks: "액션 페이싱" },
                { key: "revenue_d7", unlocks: "매출 페이싱" },
              ],
              "5-11": [
                { key: "channel", unlocks: "채널별 퍼널 분리" },
                { key: "country", unlocks: "국가별 퍼널" },
                { key: "platform", unlocks: "OS별 퍼널" },
                { key: "revenue_d7", unlocks: "매출 단계까지 퍼널 확장" },
                { key: "actions", unlocks: "액션 단계 (installs 다음)" },
              ],
              "5-12": [
                { key: "channel", unlocks: "채널 축" },
                { key: "country", unlocks: "국가 축" },
                { key: "platform", unlocks: "OS 축" },
                { key: "campaign_name", unlocks: "캠페인 드릴다운" },
                { key: "impressions", unlocks: "CTR/CPM 지표" },
                { key: "clicks", unlocks: "CTR/CVR 지표" },
                { key: "revenue_d7", unlocks: "ROAS 지표" },
                { key: "actions", unlocks: "CPA 지표" },
              ],
              "5-13": [
                { key: "impressions", unlocks: "CTR/CPM 카드" },
                { key: "clicks", unlocks: "CTR/CVR 카드" },
                { key: "actions", unlocks: "CPA 카드" },
                { key: "revenue_d7", unlocks: "ROAS 카드" },
                { key: "channel", unlocks: "(향후) 채널 분해" },
              ],
              "5-14": [
                { key: "channel", unlocks: "채널별 이상 분리 감지" },
                { key: "installs", unlocks: "설치·CVR 이상 감지" },
                { key: "actions", unlocks: "액션·CPA 이상 감지" },
                { key: "clicks", unlocks: "CTR 이상 감지" },
                { key: "impressions", unlocks: "노출·CPM 이상 감지" },
                { key: "revenue_d7", unlocks: "매출·ROAS 이상 감지" },
              ],
              "5-16": [
                { key: "channel", unlocks: "채널별 ROAS 성숙 분리" },
                { key: "campaign_name", unlocks: "캠페인별 성숙" },
                { key: "revenue_d0", unlocks: "D0 ROAS (성숙곡선 시작점)" },
                { key: "revenue_d7", unlocks: "D7 ROAS" },
                { key: "revenue_d14", unlocks: "D14 ROAS (외삽 정확도 ↑)" },
                {
                  key: "revenue_d30",
                  unlocks: "D30 ROAS (경험적 비율 anchor · 충분성 진단)",
                },
                { key: "revenue_d60", unlocks: "D60 ROAS (장기 곡선 정밀도 ↑)" },
                { key: "revenue_d90", unlocks: "D90 ROAS (실측 성숙 검증)" },
                { key: "revenue_d180", unlocks: "D180 ROAS (완전 성숙 기준)" },
                { key: "revenue_d360", unlocks: "D360 ROAS (연간 ROAS 실측)" },
              ],
              "5-15": [
                { key: "experiment_id", unlocks: "실험별 분리 readout" },
                { key: "spend", unlocks: "iROAS (증분 매출 / 비용)" },
                { key: "revenue_d7", unlocks: "증분 매출·iROAS" },
                { key: "arm_label", unlocks: "그룹 라벨 표시" },
              ],
              "5-18": [
                {
                  key: "mmm_platform",
                  unlocks: "플랫폼(iOS/AOS) 차원 — 상단 셀렉트로 세그먼트별 분석",
                },
                {
                  key: "mmm_react",
                  unlocks: "React 타깃 모델 (Reg와 별도 — 카니발 핵심)",
                },
                {
                  key: "ch_google_cbua",
                  unlocks: "Google CBUA 채널 (line_off와 공선 → 레짐 흡수)",
                },
                { key: "ch_meta", unlocks: "Meta 채널" },
                { key: "ch_tiktok", unlocks: "TikTok 채널" },
                {
                  key: "ch_brand",
                  unlocks: "Brand 채널 (강한 드라이버 — 포함 권장)",
                },
                { key: "d_prelny", unlocks: "설날 전주 더미" },
                { key: "d_seollal", unlocks: "설날 더미 (시트 audit)" },
                { key: "d_chuseokonly", unlocks: "추석 더미" },
                { key: "d_postchuwk", unlocks: "추석 후주 더미" },
                { key: "d_otherhol", unlocks: "기타 공휴일 더미" },
              ],
              "5-21": [
                {
                  key: "campaign_id",
                  unlocks: "캠페인 단계 분해 — 매핑 안 하면 채널→소재 2단계로 동작",
                },
                {
                  key: "creative_id",
                  unlocks:
                    "소재 단계 딥다이브(§4) — 매핑 안 하면 채널/캠페인까지만 분해",
                },
                {
                  key: "creative_url",
                  unlocks:
                    "소재별 결과(§4)에 소재 링크 표시 — 클릭 시 새 창(merge 시 비용 최대 소재 URL)",
                },
                {
                  key: "impressions",
                  unlocks: "소재별 CTR 비교(§4) — clicks와 함께 매핑 시 활성화",
                },
                {
                  key: "clicks",
                  unlocks: "소재별 CTR 비교(§4) — impressions와 함께 매핑 시 활성화",
                },
              ],
            };
