// @vitest-environment jsdom
import { confirmReviewSave } from "@/test/reviewSaveBoundary";
import { beforeEach, expect, it } from "vitest";
import { render, fireEvent, screen, cleanup } from "@testing-library/react";
import ResultActionCard from "./ResultActionCard";
import DecisionFollowUp from "@/components/weekly-review/DecisionFollowUp";
import { publishedToolIds } from "@/lib/routeMap";
import { toolDecisionGoals } from "@/lib/decisionGoals";
import { readDecisionPlan } from "@/lib/decisionPlan";
import { useAppStore } from "@/store/useDataStore";
const ids = publishedToolIds();
beforeEach(() => useAppStore.setState({ decisionRecords: [], csvData: { raw: [], mapping: {}, headers: [], importSource: "upload" }, decisionPersistenceEnabled: false }));
it("has a nonempty published-tool coverage boundary", () => expect(ids.length).toBeGreaterThanOrEqual(20));
it.each(ids)("%s creates first and follow-up decisions with registered goals through the shared result UI", toolId => {
  const goals = toolDecisionGoals(toolId);
  const view = render(<ResultActionCard toolId={toolId} headline="Observed evidence" analysisBasis={false} />);
  fireEvent.click(view.container.querySelector(".decision-review-launch"));
  expect([...screen.getByLabelText("목표 (성공의 정의)").options].map(option => option.value)).toEqual([...goals.map(goal => goal.key), ""]);
  fireEvent.change(screen.getByLabelText("무엇을 바꿀까요?"), { target: { value: "Test the next hypothesis" } });
  fireEvent.click(screen.getByRole("button", { name: "다음 검토로 저장" })); confirmReviewSave();
  const first = useAppStore.getState().decisionRecords[0];
  expect(first.goalMetric).toBe(goals[0].key);
  expect(first.goalDirection).toBe(goals[0].direction);
  cleanup();
  render(<DecisionFollowUp record={{ ...first, actual: "Observation", learning: "Next hypothesis" }} />);
  fireEvent.click(screen.getByRole("button", { name: "배운 점으로 다음 결정 만들기" }));
  fireEvent.change(screen.getByLabelText("다음에 실행할 행동"), { target: { value: "Follow-up action" } });
  const chosen = goals.at(-1);
  fireEvent.change(screen.getByLabelText("다음 결정의 목표"), { target: { value: chosen.key } });
  fireEvent.click(screen.getByRole("button", { name: "다음 결정 저장", exact: true })); confirmReviewSave();
  const child = useAppStore.getState().decisionRecords.find(record => record.parentDecisionId === first.id);
  expect(child.goalMetric).toBe(chosen.key); expect(child.metric).toBe(chosen.label);
  expect(child.goalDirection).toBe(chosen.direction);
});
it.each(["ko", "en"])("%s saves MMM → holdout → organic user recovery with quantitative criteria", locale => {
  const en = locale === "en";
  render(<DecisionFollowUp locale={locale} record={{ id: "mmm", toolId: "5-18-mmm", action: "Review attribution", actual: "Model output", learning: "Validate channel incrementality", goalMetric: "roas", metric: "ROAS" }} />);
  fireEvent.click(screen.getByRole("button", { name: en ? "Turn this learning into the next decision" : "배운 점으로 다음 결정 만들기" }));
  const change = (ko, eng, value) => fireEvent.change(screen.getByLabelText(en ? eng : ko), { target: { value } });
  change("다음에 실행할 행동", "Next action", "Hold out Google brand");
  change("다음 결정의 목표", "Goal for the next decision", "rerun:organic_users");
  change("검토 방법", "Review method", "holdout");
  change("대상 채널·집단", "Target channel / group", "Google brand");
  change("비교군", "Comparison group", "Control regions");
  change("관측 기간", "Observation window", "Oct 1–14");
  change("성공 기준 유형", "Success threshold type", "increase_percent");
  expect(screen.getByRole("button", { name: en ? "Save next decision" : "다음 결정 저장", exact: true }).disabled).toBe(true);
  change("목표값", "Target value", "10"); change("측정 단위", "Measurement unit", "people"); change("이번 결정의 기준값", "Baseline for this decision", "5000");
  fireEvent.click(screen.getByRole("button", { name: en ? "Save next decision" : "다음 결정 저장", exact: true })); confirmReviewSave();
  const child = useAppStore.getState().decisionRecords[0];
  expect(child.goalMetric).toBe("rerun:organic_users");
  expect(readDecisionPlan(child.reviewPlan)).toMatchObject({ method: "holdout", target: "Google brand", mode: "increase_percent", value: "10", baseline: "5000", unit: "people" });
  expect(child.baseline).toBe("");
});
